### ISSUE TITLE
Qbit not working at all after the latest commit

### ISSUE THREAD

**Issue by Nobody12541** [anasty17/mirror-leech-telegram-bot#1000]
Hi you just closed my previous topic saying that i edited your repo, no i did not edit your repo in any way.

Just to be clear after you said i edited you repo, i deleted my repo and forked your repo again and deleted heroku app again. But still the same issue.
Bot is not working with qbit commands. 
Please try to use a qbit command on your bot. Look it is your commit.
![Screenshot_2022_0828_211607](https://user-images.githubusercontent.com/101923792/187083782-c39b6854-e458-4a63-bcd9-22df684cf054.png)

And the error in logs is this :
2022-08-28 15:33:01,556 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
2022-08-28T15:33:01.557284+00:00 app[web.1]: Traceback (most recent call last):
2022-08-28T15:33:01.557285+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
2022-08-28T15:33:01.557286+00:00 app[web.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2022-08-28T15:33:01.557286+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror_leech.py", line 214, in qb_mirror
2022-08-28T15:33:01.557287+00:00 app[web.1]:     _mirror_leech(context.bot, update.message, isQbit=True)
2022-08-28T15:33:01.557287+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror_leech.py", line 71, in _mirror_leech
2022-08-28T15:33:01.557287+00:00 app[web.1]:     link = re_split(r"pswd:|\|", link)[0]
2022-08-28T15:33:01.557288+00:00 app[web.1]: UnboundLocalError: local variable 'link' referenced before assignment

**Comment by SiGLAka** [comment]
Same qbmirror & mirror just working fine but mirror/qbmirror d or s not working
It was working just fine sometime before

**Comment by anasty17** [comment]
Try now
