### ISSUE TITLE
bt_select getting Error

### ISSUE THREAD

**Issue by ketela7** [anasty17/mirror-leech-telegram-bot#1006]
![Screenshot_2022-08-29-18-22-50-325_ir ilmili telegraph](https://user-images.githubusercontent.com/103868701/187190635-84661b61-22fd-4dcd-80fa-5fc24ed62107.jpg)

2022-08-29 11:19:10,580 - web.wserver - ERROR - File IDs must be integers Errored in paused
2022-08-29 11:19:11,586 - web.wserver - INFO - Verified! Hash: 84a5c3ded1bc2222ee21220d1896c16207b5dd68
2022-08-29 11:19:14,016 - web.wserver - ERROR - File IDs must be integers Errored in paused
2022-08-29 11:19:15,024 - web.wserver - INFO - Verified! Hash: 84a5c3ded1bc2222ee21220d1896c16207b5dd68
2022-08-29 11:21:45,334 - web.wserver - ERROR - File IDs must be integers Errored in paused
2022-08-29 11:21:46,340 - web.wserver - INFO - Verified! Hash: 1b7249a234075116bacf06de8473765a652ec3bc
2022-08-29 11:21:58,931 - web.wserver - INFO - Verified! Hash: 1b7249a234075116bacf06de8473765a652ec3bc

and 

2022-08-29 11:34:19,773 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/bt_select.py", line 38, in select
    if dl.status() not in [MirrorStatus.STATUS_DOWNLOADING, MirrorStatus.STATUS_PAUSED, MirrorStatus.STATUS_WAITING]:
UnboundLocalError: local variable 'dl' referenced before assignment

I make private group with my bot, and i got that!.

**Comment by anasty17** [comment]
Bruh seems u edit in code nothing wrong here!

**Comment by anasty17** [comment]
Send torrent let mr try to check this web error .
But regarding dl not referenced before this shouldn't happen!

**Comment by ketela7** [comment]
the cause is I use auto download rss with command.  and the sender of the command is not me, so this will bring up 'this not u'.  okay.  sorry bruh. 😂😂

**Comment by anasty17** [comment]
> the cause is I use auto download rss with command. and the sender of the command is not me, so this will bring up 'this not u'. okay. sorry bruh. 😂😂

Also this shouldn't happen! If u r the owner!
