### ISSUE TITLE
Got some issue

### ISSUE THREAD

**Issue by alok99-git** [anasty17/mirror-leech-telegram-bot#102]
- When i do /leech i got this error, but file uploaded
Log : 
```
2021-11-30T06:57:03.166792+00:00 app[web.1]: Exception in thread Thread-5:
2021-11-30T06:57:03.166804+00:00 app[web.1]: Traceback (most recent call last):
2021-11-30T06:57:03.166820+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-11-30T06:57:03.167059+00:00 app[web.1]:     self.run()
2021-11-30T06:57:03.167081+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-11-30T06:57:03.167272+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2021-11-30T06:57:03.167301+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 21, in __onDownloadStarted
2021-11-30T06:57:03.167383+00:00 app[web.1]:     if STOP_DUPLICATE and dl is not None and not dl.getListener().isLeech:
2021-11-30T06:57:03.167416+00:00 app[web.1]: AttributeError: 'TgUploadStatus' object has no attribute 'getListener'
```

- Stop duplicate not working
Log : 
```
2021-11-30T07:12:53.083576+00:00 app[web.1]: Exception in thread Thread-2:
2021-11-30T07:12:53.083606+00:00 app[web.1]: Traceback (most recent call last):
2021-11-30T07:12:53.083639+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-11-30T07:12:53.085012+00:00 app[web.1]:     self.run()
2021-11-30T07:12:53.085093+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-11-30T07:12:53.085642+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2021-11-30T07:12:53.085711+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 21, in __onDownloadStarted
2021-11-30T07:12:53.086016+00:00 app[web.1]:     if STOP_DUPLICATE and dl is not None and not dl.getListener().isLeech:
2021-11-30T07:12:53.086136+00:00 app[web.1]: AttributeError: 'UploadStatus' object has no attribute 'getListener'
```

LINK : `https://sourceforge.net/projects/gabutbuild/files/Simple/simplekernel-11.0-ginkgo-20211129-0740.zip/download`

**Comment by anasty17** [comment]
@alok99-git That's bcz file size is too small

**Comment by anasty17** [comment]
@alok99-git Will add Exception for this

**Comment by alok99-git** [comment]
> @alok99-git That's bcz file size is too small

Oh right ! I try big file, stop duplicate working & i don't get this error
