### ISSUE TITLE
'NoneType' object has no attribute 'state'

### ISSUE THREAD

**Issue by iron-heart-x** [anasty17/mirror-leech-telegram-bot#1026]
**Describe the bug**
'NoneType' object has no attribute 'state'

/qbmirror d::1440
Before Upload

When I send /status no reply.
but in log
```
2022-09-02 11:04:37,402 - bot - ERROR - : while getting torrent info
2022-09-02 11:06:36,288 - bot - INFO - Cleaning Download: /usr/src/app/downloads/511
2022-09-02 11:06:36,913 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 11:06:39,287 - bot - ERROR - 511
2022-09-02 11:17:55,786 - bot - INFO - Cleaning Download: /usr/src/app/downloads/492
2022-09-02 11:17:56,390 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 11:17:58,786 - bot - ERROR - 492
2022-09-02 11:23:15,234 - bot - INFO - Cleaning Download: /usr/src/app/downloads/507
2022-09-02 11:23:15,978 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 11:23:18,232 - bot - ERROR - 507
2022-09-02 11:26:34,938 - bot - INFO - Cleaning Download: /usr/src/app/downloads/494
2022-09-02 11:26:35,561 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 11:26:37,938 - bot - ERROR - 494
2022-09-02 11:28:35,557 - bot - INFO - Cleaning Download: /usr/src/app/downloads/505
2022-09-02 11:28:36,187 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 11:28:38,556 - bot - ERROR - 505
2022-09-02 11:53:46,958 - bot - INFO - Cleaning Download: /usr/src/app/downloads/493
2022-09-02 11:53:47,647 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 11:53:49,959 - bot - ERROR - 493
2022-09-02 12:04:47,215 - bot - INFO - Cleaning Download: /usr/src/app/downloads/491
2022-09-02 12:04:48,031 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 12:04:50,214 - bot - ERROR - 491
2022-09-02 13:33:37,947 - bot - INFO - Cleaning Download: /usr/src/app/downloads/539
2022-09-02 13:33:38,647 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 13:33:40,943 - bot - ERROR - 539
2022-09-02 13:45:35,446 - bot - INFO - Cleaning Download: /usr/src/app/downloads/543
2022-09-02 13:45:36,095 - bot - ERROR - 'NoneType' object has no attribute 'state'
2022-09-02 13:45:38,450 - bot - ERROR - 543
2022-09-02 13:45:43,830 - bot - INFO - https://www.1tamilmv.cyou/applications/core/interface/file/attachment.php?id=95449&key=5ef296b5ef2216c1225add731816eda9
2022-09-02 13:45:44,180 - bot - INFO - https://www.1tamilmv.cyou/applications/core/interface/file/attachment.php?id=95448&key=8da706ba9eff152ff5807765ec421eaf
2022-09-02 13:45:45,624 - bot - INFO - QbitDownload started: www.1TamilMV.cyou - Ivy Bean (2022) 1080p - x264 - [Taml + Tel + Hin + Eng] - (DD+ 5.1 - 640Kbps) - 4.8GB - ESub - Hash: bb1f91d01f488a47707f1ce4aa03faac3f7f084c
2022-09-02 13:45:45,973 - bot - INFO - QbitDownload started: www.1TamilMV.cyou - Ivy Bean (2022) 720p - x264 - [Taml + Tel + Hin + Eng] - (DD+ 5.1 - 192Kbps) - 1.7GB - ESub - Hash: 554db4ee1ec3a271029f2b3e05628dbcd49fd978
2022-09-02 13:45:48,633 - bot - INFO - Checking File/Folder if already in Drive
2022-09-02 13:45:48,634 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 30.json service account
2022-09-02 13:46:06,977 - bot - INFO - Checking File/Folder if already in Drive
2022-09-02 13:46:06,977 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 91.json service account
2022-09-02 13:46:27,211 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/mirror_status.py", line 38, in mirror_status
    sendStatusMessage(update.message, context.bot)
  File "/usr/src/app/bot/helper/telegram_helper/message_utils.py", line 147, in sendStatusMessage
    progress, buttons = get_readable_message()
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 153, in get_readable_message
    if download.status() == MirrorStatus.STATUS_DOWNLOADING:
  File "/usr/src/app/bot/helper/mirror_utils/status_utils/qbit_download_status.py", line 58, in status
    download = self.__info.state
AttributeError: 'NoneType' object has no attribute 'state'
2022-09-02 14:04:50,510 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/mirror_status.py", line 38, in mirror_status
    sendStatusMessage(update.message, context.bot)
  File "/usr/src/app/bot/helper/telegram_helper/message_utils.py", line 147, in sendStatusMessage
    progress, buttons = get_readable_message()
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 153, in get_readable_message
    if download.status() == MirrorStatus.STATUS_DOWNLOADING:
  File "/usr/src/app/bot/helper/mirror_utils/status_utils/qbit_download_status.py", line 58, in status
    download = self.__info.state
AttributeError: 'NoneType' object has no attribute 'state'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/100769932/188165758-cbb5db16-80c7-4ca2-8823-62afa700fa9a.png)

**Comment by anasty17** [comment]
Don't copy paste the logs! /log and send the file
