### ISSUE TITLE
Download Getting stucked at 100% when using aria2c mirror

### ISSUE THREAD

**Issue by MotherFatherGoodManner** [anasty17/mirror-leech-telegram-bot#1075]
Here is the Log. 
FYI: I'm not using Seeding. just using /mirror magnet link

2022-09-12T14:26:57.515828+00:00 app[worker.1]: 2022-09-12 14:26:57,515 - bot - INFO - QbitDownload started: Thor: Love and Thunder (2022) IMAX (1080p DSNP WEB-DL x265 HEVC 10bit EAC3 5.1 Silence) [QxR] - Hash: 1086bbe163fb17d669706bd629a6cc4f7fbd33c3
2022-09-12T14:26:57.518859+00:00 app[worker.1]: added qb task without selecting
2022-09-12T14:27:06.525380+00:00 app[worker.1]: 2022-09-12 14:27:06,525 - bot - INFO - Checking File/Folder if already in Drive
2022-09-12T14:27:06.525556+00:00 app[worker.1]: 2022-09-12 14:27:06,525 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 60.json service account
2022-09-12T14:27:06.536593+00:00 app[worker.1]: 2022-09-12 14:27:06,536 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorize with token.pickle
2022-09-12T14:29:27.535273+00:00 app[worker.1]: 2022-09-12 14:29:27,534 - bot - INFO - Download completed: Thor: Love and Thunder (2022) IMAX (1080p DSNP WEB-DL x265 HEVC 10bit EAC3 5.1 Silence) [QxR]
2022-09-12T14:29:27.535913+00:00 app[worker.1]: 2022-09-12 14:29:27,535 - bot - INFO - Upload Name: Thor - Love and Thunder (2022) IMAX (1080p DSNP WEB-DL x265 HEVC 10bit EAC3 5.1 Silence)
2022-09-12T14:29:27.536059+00:00 app[worker.1]: 2022-09-12 14:29:27,535 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 83.json service account
2022-09-12T14:29:27.958827+00:00 app[worker.1]: 2022-09-12 14:29:27,958 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploading File: /usr/src/app/downloads/427003/Thor - Love and Thunder (2022) IMAX (1080p DSNP WEB-DL x265 HEVC 10bit EAC3 5.1 Silence)
2022-09-12T14:29:29.512905+00:00 app[worker.1]: 2022-09-12 14:29:29,512 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Created G-Drive Folder:
2022-09-12T14:29:29.512912+00:00 app[worker.1]: Name: Thor - Love and Thunder (2022) IMAX (1080p DSNP WEB-DL x265 HEVC 10bit EAC3 5.1 Silence)
2022-09-12T14:29:29.512913+00:00 app[worker.1]: ID: 1SQ7DMIi2kDno4b8r3A43TaYtaJGkdbaN 
2022-09-12T14:29:56.038735+00:00 app[worker.1]: 2022-09-12 14:29:56,033 - bot - INFO - onBtDownloadComplete: The Sex Lives of College Girls (2021) Season 1 S01 (1080p WEB-DL x265 HEVC 10bit AAC 5.1 Panda) - Gid: b271b539c5dddd10
2022-09-12T14:29:56.111134+00:00 app[worker.1]: Exception in thread Thread-62:
2022-09-12T14:29:56.111162+00:00 app[worker.1]: Traceback (most recent call last):
2022-09-12T14:29:56.111213+00:00 app[worker.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-09-12T14:29:56.116997+00:00 app[worker.1]:     self.run()
2022-09-12T14:29:56.117028+00:00 app[worker.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2022-09-12T14:29:56.117736+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)
2022-09-12T14:29:56.117768+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 116, in __onBtDownloadComplete
2022-09-12T14:29:56.129357+00:00 app[worker.1]:     api.client.force_pause(gid)
2022-09-12T14:29:56.129412+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 706, in force_pause
2022-09-12T14:29:56.134706+00:00 app[worker.1]:     return self.call(self.FORCE_PAUSE, [gid])  # type: ignore
2022-09-12T14:29:56.134741+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 262, in call
2022-09-12T14:29:56.137059+00:00 app[worker.1]:     return self.res_or_raise(self.post(payload))
2022-09-12T14:29:56.137143+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 389, in res_or_raise
2022-09-12T14:29:56.137832+00:00 app[worker.1]:     raise Client.response_as_exception(response)
2022-09-12T14:29:56.139282+00:00 app[worker.1]: aria2p.client.ClientException: GID#b271b539c5dddd10 cannot be paused now

**Comment by anasty17** [comment]
Seems abuse! How many tasks u have added ?! Send full logs /log and send
