### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Kadiya99** [anasty17/mirror-leech-telegram-bot#1085]
I'm stop the bot for clear the containers and try to run again. But unfortunately this error showing.

root@ip-172-26-43-212:~/sdbot# sudo docker run -p 85:85 sdbot
warning: no common commits
2022-09-18 11:06:25,569 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
[2022-09-18 11:06:28 +0000] [29] [INFO] Starting gunicorn 20.1.0
[2022-09-18 11:06:28 +0000] [29] [INFO] Listening at: http://0.0.0.0:85 (29)
[2022-09-18 11:06:28 +0000] [29] [INFO] Using worker: sync
[2022-09-18 11:06:28 +0000] [56] [INFO] Booting worker with pid: 56
2022-09-18 11:06:29,125 - root - INFO - Creating client from USER_SESSION_STRING
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 145, in <module>
    with app:
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 280, in __enter__
    return self.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 563, in load_session
    await self.storage.open()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/memory_storage.py", line 61, in open
    base64.urlsafe_b64decode(self.session_string + "=" * (-len(self.session_string) % 4))
  File "/usr/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4

**Comment by anasty17** [comment]
Generate new session string for pyrogram
