### ISSUE TITLE
I

### ISSUE THREAD

**Issue by santosadrian** [anasty17/mirror-leech-telegram-bot#1093]
I'm since yerterday trying to install the bot, I solved a lot of dependencies, I tried everything... please help.
Runing Ubuntu 5.0.0-31-generic Python 3.7.13 conda

[/root/mirrorbot]:# ./start.sh
/bin/sh: 1: gunicorn: not found
Bad command line: You cannot use -d (or --daemon): qBittorrent is already running for this user.
Run application with -h option to read about command line parameters.
2022-09-24 12:57:27,121 - bot - INFO - Generating USER_SESSION_STRING
2022-09-24 12:57:27,122 - bot - INFO - Generating TELEGRAPH_TOKEN using 'LMJZaKjv' name
2022-09-24 12:57:27,333 - root - WARNING - MEGA Credentials not provided!
2022-09-24 12:57:27,334 - root - WARNING - BASE_URL_OF_BOT not provided!
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/mirrorbot/bot/__main__.py", line 20, in <module>
    from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, torrent_search, delete, speedtest, count, leech_settings
  File "/root/mirrorbot/bot/modules/mirror.py", line 25, in <module>
    from bot.helper.mirror_utils.download_utils.mega_downloader import MegaDownloadHelper
  File "/root/mirrorbot/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 3, in <module>
    from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
ImportError: cannot import name 'MegaApi' from 'mega' (/root/anaconda3/lib/python3.7/site-packages/mega/__init__.py)

**Comment by anasty17** [comment]
Use docker!
