### ISSUE TITLE
qbittorrent-nox: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mr-m85** [anasty17/mirror-leech-telegram-bot#1098]
Hi,

I need help can anyone help me fix this problem if there is no problem please

Thank You,

  [2022-09-26 19:43:41 +0700] [19] [INFO] Starting gunicorn 20.1.0
  [2022-09-26 19:43:41 +0700] [19] [INFO] Listening at: http://0.0.0.0:8081 (19)
  [2022-09-26 19:43:41 +0700] [19] [INFO] Using worker: aiohttp.GunicornWebWorker
  [2022-09-26 19:43:41 +0700] [23] [INFO] Booting worker with pid: 23
  qbittorrent-nox: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
  2022-09-26 19:43:41,665 - bot - INFO - Generating USER_SESSION_STRING
  2022-09-26 19:43:41,667 - bot - INFO - Generating TELEGRAPH_TOKEN using 'aZjfDEXp' name
  2022-09-26 19:43:42,059 - root - WARNING - MEGA Credentials not provided!
  2022-09-26 19:43:42,059 - root - WARNING - BASE_URL_OF_BOT not provided!
  2022-09-26 19:43:50,915 - bot - WARNING - Forbidden: bot was kicked from the supergroup chat
  2022-09-26 19:43:50,917 - apscheduler.scheduler - INFO - Scheduler started
  2022-09-26 19:43:50,940 - bot - INFO - Bot Started!
  2022-09-26 19:58:08,156 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
      conn = connection.create_connection(
    File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
      for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
    File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  socket.gaierror: [Errno -2] Name or service not known
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
      httplib_response = self._make_request(
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
      conn.request(method, url, **httplib_request_kw)
    File "/usr/lib/python3.8/http/client.py", line 1256, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
      self.send(msg)
    File "/usr/lib/python3.8/http/client.py", line 951, in send
      self.connect()
    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
      conn = self._new_conn()
    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
      raise NewConnectionError(
  urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd130629e20>: Failed to establish a new connection: [Errno -2] Name or service not known
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
      resp = conn.urlopen(
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
      return self.urlopen(
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
      retries = retries.increment(
    File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))
  urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.343.12.7', port=7854): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd130629e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/dist-packages/qbittorrentapi/request.py", line 401, in _request_manager
      return self._request(**kwargs)
    File "/usr/local/lib/python3.8/dist-packages/qbittorrentapi/request.py", line 452, in _request
      response = self._session.request(
    File "/usr/local/lib/python3.8/dist-packages/qbittorrentapi/request.py", line 562, in request
      return super(QbittorrentSession, self).request(method, url, **kwargs)
    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
      resp = self.send(prep, **send_kwargs)
    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
      r = adapter.send(request, **kwargs)
    File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
      raise ConnectionError(e, request=request)
  requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.343.12.7', port=7854): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd130629e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
      self._result = self.pooled_function(*self.args, **self.kwargs)
    File "/usr/src/app/bot/__main__.py", line 72, in restart
      fs_utils.clean_all()
    File "/usr/src/app/bot/helper/ext_utils/fs_utils.py", line 32, in clean_all
      get_client().torrents_delete(torrent_hashes="all", delete_files=True)
    File "/usr/src/app/bot/__init__.py", line 96, in get_client
      qb_client.auth_log_in()
    File "/usr/local/lib/python3.8/dist-packages/qbittorrentapi/auth.py", line 96, in auth_log_in
      self._post(_name=APINames.Authorization, _method="login", data=creds, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/qbittorrentapi/request.py", line 350, in _post
      return self._request_manager(
    File "/usr/local/lib/python3.8/dist-packages/qbittorrentapi/request.py", line 411, in _request_manager
      raise APIConnectionError(error_message, response=response)
  qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.343.12.7', port=7854): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd130629e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"))

**Comment by anasty17** [comment]
Update ur code
