### ISSUE TITLE
rss not working

### ISSUE THREAD

**Issue by THU-Pieris** [anasty17/mirror-leech-telegram-bot#1232]
**Describe the bug**
rss not working. error message:
```
2022-11-20 19:57:52,085 - apscheduler.executors.default - INFO - Running job "RSS (trigger: interval[0:30:00], next run at: 2022-11-20 20:27:52 UTC)" (scheduled at 2022-11-20 19:57:52.081324+00:00)
2022-11-20 19:57:52,088 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/src/app/bot/modules/rss.py", line 186, in rss_monitor
    for title, data in list(rss_dict.items()):
UnboundLocalError: local variable 'list' referenced before assignment
```

**To Reproduce**
Add rss subscription and wait.

**Expected behavior**
rss link is automatically sent to channel I specify, and downloading/uploading starts.

**Additional context**
I login to mongoDB and checked, the rss links are there. Tried to update my bot to latest but error still exists.

**Comment by anasty17** [comment]
Fixed thanks for reporting.
https://github.com/anasty17/mirror-leech-telegram-bot/commit/7f204a55134b857814cc90d1360619b3ad21fff7

**Comment by anasty17** [comment]
Connection issues
