### ISSUE TITLE
 No module named 'psycopg2'

### ISSUE THREAD

**Issue by sennoncap** [anasty17/mirror-leech-telegram-bot#1279]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 14, in <module>
    from .helper.ext_utils.db_handler import DbManger
  File "/usr/src/app/bot/helper/ext_utils/db_handler.py", line 2, in <module>
    from psycopg2 import connect, DatabaseError
ModuleNotFoundError: No module named 'psycopg2'
 

i am facing with this error ...
i don't know how to fix it ..
help me

**Comment by anasty17** [comment]
Update ur code

**Comment by sennoncap** [comment]
thanks sir .. i will try

**Comment by sennoncap** [comment]
i update to  latest ,but error still occur sir..
