### ISSUE TITLE
ImportError: cannot import name 'MegaApi' from 'mega.mega'

### ISSUE THREAD

**Issue by devabdulharis** [anasty17/mirror-leech-telegram-bot#1282]
2022-12-14 17:23:12,278 - root - INFO - Creating client from BOT_TOKEN
2022-12-14 17:23:12,282 - root - WARNING - MEGA API KEY not provided!
2022-12-14 17:23:12,283 - root - WARNING - MEGA Credentials not provided!
Bad command line: 
You cannot use -d (or --daemon): qBittorrent is already running for this user.
Run application with -h option to read about command line parameters.
2022-12-14 17:23:13,145 - root - INFO - Initializing Aria2c
[2022-12-14 17:23:13 +0000] [16107] [INFO] Starting gunicorn 20.1.0
[2022-12-14 17:23:13 +0000] [16107] [INFO] Listening at: http://0.0.0.0:8000 (16107)
[2022-12-14 17:23:13 +0000] [16107] [INFO] Using worker: sync
[2022-12-14 17:23:13 +0000] [16123] [INFO] Booting worker with pid: 16123
2022-12-14 17:23:17,339 - bot - INFO - Creating Telegraph Account
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/usb/Mirror/mirror-leech/bot/__main__.py", line 18, in <module>
    from .modules import authorize, list, cancel_mirror, mirror_status, mirror_leech, clone, ytdlp, \
  File "/mnt/usb/Mirror/mirror-leech/bot/modules/mirror_leech.py", line 15, in <module>
    from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download
  File "/mnt/usb/Mirror/mirror-leech/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 5, in <module>
    from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
ImportError: cannot import name 'MegaApi' from 'mega.mega' (/mnt/usb/Mirror/mirror-leech/venv/lib/python3.8/site-packages/python_mega-0.1.0-py3.8.egg/mega/mega.py)

I'am using python 3.8

**Comment by anasty17** [comment]
Use my docker

**Comment by devabdulharis** [comment]
[image: image.png]

it's same issue using docker-compose.

**Comment by devabdulharis** [comment]
if iam using command ./start.sh without docker i got error mega. and then
see cat log.txt it same stuck after creating telegraph account.
its same issue too when iam try using docker.
