### ISSUE TITLE
Pyrogram not started

### ISSUE THREAD

**Issue by pradeishc** [anasty17/mirror-leech-telegram-bot#1358]
pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")

Could you tell what I have to do ?

**Comment by anasty17** [comment]
Using USER_SESSION_STRING? u should explain! If yes then generate new session_string! Read the error message! I can know without knowing what u have done.

**Comment by pradeishc** [comment]
i regenerated 3 times with python3 generate_string_session.py command still the error persists

**Comment by pradeishc** [comment]
warning: no common commits
2023-02-10 13:00:06,439 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2023-02-10 13:00:07,720 - root - INFO - Creating client from USER_SESSION_STRING
2023-02-10 13:00:08,357 - pyrogram.connection.connection - INFO - Connecting...
2023-02-10 13:00:08,403 - pyrogram.connection.connection - INFO - Connected! Production DC5 - IPv4
2023-02-10 13:00:08,404 - pyrogram.session.session - INFO - NetworkTask started
2023-02-10 13:00:08,673 - pyrogram.session.session - INFO - Session initialized: Layer 151
2023-02-10 13:00:08,673 - pyrogram.session.session - INFO - Device: CPython 3.8.10 - Pyrogram 2.0.93
2023-02-10 13:00:08,673 - pyrogram.session.session - INFO - System: Linux 5.15.0-1029-oracle (en)
2023-02-10 13:00:08,673 - pyrogram.session.session - INFO - Session started
2023-02-10 13:00:08,737 - pyrogram.session.session - INFO - PingTask started
2023-02-10 13:00:08,790 - pyrogram.session.session - INFO - PingTask stopped
2023-02-10 13:00:08,791 - pyrogram.connection.connection - INFO - Disconnected
2023-02-10 13:00:08,791 - pyrogram.session.session - INFO - NetworkTask stopped
2023-02-10 13:00:08,791 - pyrogram.session.session - INFO - Session stopped
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 163, in <module>
    with app:
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 290, in __enter__
    return self.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 68, in start
    await self.invoke(raw.functions.updates.GetState())
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")


This is the total error I'm getting
