### ISSUE TITLE
Error when executing /ping

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1362]
**Describe the bug**
When I execute `/ping` bot won't respond.
I check logs there is a error `NameError: name 'event' is not defined`

**To Reproduce**
1. Used this Command `/ping`
2. When I execute /ping
3. Check logs
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10753549/log.27.txt)

**Expected behavior**
Bot responds to `/ping` command

**Additional context**

`
pyrogram.dispatcher - ERROR - name 'event' is not defined
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
app_1  |     await handler.callback(self.client, *args)
app_1  |   File "/usr/src/app/bot/__main__.py", line 83, in ping
app_1  |     reply = await sendMessage(event, "Starting Ping")
app_1  | NameError: name 'event' is not defined
app_1  | 2023-02-16 08:08:05,437 - apscheduler.executors.default - INFO - Running job "RSS (trigger: interval[0:10:00], next run at: 2023-02-16 08:18:05 UTC)" (scheduled at 2023-02-16 08:08:05.432040+00:00)
app_1  | 2023-02-16 08:08:05,439 - apscheduler.executors.default - ERROR - Job "RSS (trigger: interval[0:10:00], next run at: 2023-02-16 08:18:05 UTC)" raised an exception
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/src/app/bot/modules/rss.py", line 561, in rssMonitor
app_1  |     if data['paused']:
app_1  | TypeError: list indices must be integers or slices, not str
app_1  |
app_1  | During handling of the above exception, another exception occurred:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
app_1  |     retval = await job.func(*job.args, **job.kwargs)
app_1  |   File "/usr/src/app/bot/modules/rss.py", line 615, in rssMonitor
app_1  |     LOGGER.error(f"{e} Feed Name: {title} - Feed Link: {data['link']}")
app_1  | TypeError: list indices must be integers or slices, not str
`

**Comment by erickyun** [comment]
> Try now.

rss works BUT uploading is not working?
The bot downloads the file but it won't upload it to neither telegram or gdrive.

And status won't change it keeps showing 0.00% .
Status shows downloading, uploading file size tho but percentage won't change?

[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10756207/log00.txt)

**Comment by erickyun** [comment]
Also sir how does auto downloading work now?

Bot sends cmd like 
`
/qm https://randomsitetorrent/xxx.torrent
Tag: Name userid
`
But it won't start auto downloading?

**Comment by anasty17** [comment]
I didn't test this. U add rss for yt-dlp?

**Comment by anasty17** [comment]
Can u send logs when rss send item ro mirror/leech

**Comment by anasty17** [comment]
> Also sir I know it is not related and your bussy right now fixing the bot but How does auto downloading work now?
> 
> Bot sends cmd like `/qm https://randomsitetorrent/xxx.torrent Tag: UserName userid` But it won't start auto downloading?
> 
> Before the cmd was like `/qm https://randomsitetorrent/xxx.torrent` And auto downloading would work.

RSS_USER_SESSION_STRING removed use USER_SESSION_STRING instead

**Comment by erickyun** [comment]
> > Also sir I know it is not related and your bussy right now fixing the bot but How does auto downloading work now?
> > Bot sends cmd like `/qm https://randomsitetorrent/xxx.torrent Tag: UserName userid` But it won't start auto downloading?
> > Before the cmd was like `/qm https://randomsitetorrent/xxx.torrent` And auto downloading would work.
> 
> RSS_USER_SESSION_STRING removed use USER_SESSION_STRING instead If u r using it... or use linked channel

`/rss` and `/l` seems to work.
But `/qm` and `/m` are giving error I keep getting token.pickle not found! But I did send token.pickle to bot?

[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10757487/log.1.txt)

Also `/y `yl` command give Unable to extract uploader id ERROR?
[log (1).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10757517/log.1.txt)

**Comment by anasty17** [comment]
Ok. I will fix this. But u r using rss with yt-dlp?

**Comment by erickyun** [comment]
> Ok. I will fix this. But u r using rss with yt-dlp?

No sir /qm only

**Comment by anasty17** [comment]
Ok problem in uploading private file

**Comment by anasty17** [comment]
> > Ok problem in uploading private file
> 
> Yes uploading private file seem not to work.
> 
> Also the "Unable to extract uploader id" yt-dlp problem seem yt-dlp problem not bot fault. [yt-dlp/yt-dlp#6247](https://github.com/yt-dlp/yt-dlp/issues/6247)

Yes it's from yt-dlp

**Comment by erickyun** [comment]
> Fixed

I'm still getting error?

`
app_1  | 2023-02-16 17:34:42,266 - bot - INFO - Download from Telegram: Screenshot_2023-02-16-17-39-04-494_com.chess.jpg
app_1  | 2023-02-16 17:34:42,598 - bot - INFO - Download completed: Screenshot_2023-02-16-17-39-04-494_com.chess.jpg
app_1  | 2023-02-16 17:34:42,599 - bot - INFO - Upload Name: Screenshot_2023-02-16-17-39-04-494_com.chess.jpg
app_1  | 2023-02-16 17:34:42,600 - bot.helper.mirror_utils.upload_utils.gdriveTools - ERROR - token.pickle not found!
app_1  | 2023-02-16 17:34:45,613 - google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
app_1  | 2023-02-16 17:34:48,618 - google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
app_1  | 2023-02-16 17:34:51,622 - google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
app_1  | 2023-02-16 17:34:51,623 - google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
app_1  | 2023-02-16 17:34:51,624 - pyrogram.dispatcher - ERROR - Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
app_1  |     await handler.callback(self.client, *args)
app_1  |   File "/usr/src/app/bot/modules/mirror_leech.py", line 219, in mirror
app_1  |     await _mirror_leech(client, message)
app_1  |   File "/usr/src/app/bot/modules/mirror_leech.py", line 132, in _mirror_leech
app_1  |     await TelegramDownloadHelper(listener).add_download(reply_to, f'{path}/', name)
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 134, in add_download
app_1  |     await self.__download(message, path)
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 87, in __download
app_1  |     await self.__onDownloadComplete()
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 74, in __onDownloadComplete
app_1  |     await self.__listener.onDownloadComplete()
app_1  |   File "/usr/src/app/bot/helper/listener.py", line 257, in onDownloadComplete
app_1  |     await sync_to_async(drive.upload, up_name)
app_1  |   File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 297, in sync_to_async
app_1  |     return await future
app_1  |   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
app_1  |     result = self.fn(*self.args, **self.kwargs)
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 196, in upload
app_1  |     self.__service = self.__authorize()
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 95, in __authorize
app_1  |     return build('drive', 'v3', credentials=credentials, cache_discovery=False)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
app_1  |     return wrapped(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py", line 298, in build
app_1  |     service = build_from_document(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
app_1  |     return wrapped(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py", line 580, in build_from_document
app_1  |     credentials = _auth.default_credentials(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_auth.py", line 57, in default_credentials
app_1  |     credentials, _ = google.auth.default(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/google/auth/_default.py", line 653, in default
app_1  |     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
app_1  | google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
`

**Comment by anasty17** [comment]
Update ur repo and upload token.pickle

**Comment by erickyun** [comment]
I did sir just now again. But it won't upload private files?
Tried with account.zip but I got also error?

`
W
app_1  | unzip:  cannot find or open accounts.zip, accounts.zip.zip or accounts.zip.ZIP.
app_1  | chmod: cannot access 'accounts': No such file or directory
`

**Comment by anasty17** [comment]
Yeah 10 min and i will push fix for both. Thanks for reporting

**Comment by erickyun** [comment]
> Yeah 10 min and i will push fix for both. Thanks for reporting

Thank you, uploading private files seems the work. 👍
But bot send weird error when I check log like
`ERROR - cannot encode object: <generator object _make_delegate_method.<locals>.method at 0x7f97c6287ae0>, of type: <class 'generator'` 
[Log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10762151/Log.2.txt)

**Comment by anasty17** [comment]
I will fix it tomorrow

**Comment by erickyun** [comment]
> I will fix it tomorrow

I did just update Bot repo and
When I send account.zip. I'm getting now?
`app_1  | caution: filename not matched:  -w`

And bot does not read `.netrc` or cookies.txt when I execute /yl I'm getting `This video is for premium members only` error?

**Comment by anasty17** [comment]
U r up to date ? Upload file wasn't working. Try now and s

**Comment by erickyun** [comment]
> U r up to date ? Upload file wasn't working. Try now and tell me. 

Yes I'm up to date sir. `commit 3690938` and everything is working fine now. Private files works. 👍👍🙂

> I prefer to contact me on telegram please!!
I'm sorry for the inconvenience sir. I will try next time from TG.

I'm sending last time from here only because I think it is the last time and a mirror error sir.

Rightnow everything works fine there no problem with uploading private files but bot still shows error message in log, when uploading and deleting accounts.zip ?
Even though bot uploads the accounts.zip private file without any problem? Bot still shows error `caution: filename not matched:  -w` in log. Also same error is on bot startup log.

[Here log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10771974/log.txt)

**Comment by anasty17** [comment]
Yeah this from @junedkh he told me this will only extract the json files and exclude any other file but i didn't test it lol

**Comment by anasty17** [comment]
Fixed thanks for reporting

**Comment by erickyun** [comment]
> Fixed thanks for reporting

Thank you sir👍
