### ISSUE TITLE
AttributeError: partially initialized module 'logging' has no attribute 'getLogger'

### ISSUE THREAD

**Issue by shiestapoi** [anasty17/mirror-leech-telegram-bot#1376]
how to fix it?

```root@shoukosagiri:/mnt/c/Users/Administrator/mirrorbot# bash start.sh
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/mirrorbot/update.py", line 1, in <module>
    from logging import FileHandler, StreamHandler, INFO, basicConfig, error as log_error, info as log_info
  File "/usr/lib/python3.10/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "/usr/lib/python3.10/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.10/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.10/tokenize.py", line 35, in <module>
    from token import *
  File "/mnt/c/Users/Administrator/mirrorbot/token.py", line 3, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/__init__.py", line 21, in <module>
    from .interactive import get_user_credentials
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/interactive.py", line 27, in <module>
    import google_auth_oauthlib.flow
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/flow.py", line 65, in <module>
    import google.auth.transport.requests
  File "/usr/local/lib/python3.10/dist-packages/google/auth/__init__.py", line 20, in <module>
    from google.auth._default import default, load_credentials_from_file
  File "/usr/local/lib/python3.10/dist-packages/google/auth/_default.py", line 30, in <module>
    import google.auth.transport._http_client
  File "/usr/local/lib/python3.10/dist-packages/google/auth/transport/_http_client.py", line 27, in <module>
    _LOGGER = logging.getLogger(__name__)
AttributeError: partially initialized module 'logging' has no attribute 'getLogger' (most likely due to a circular import)```

**Comment by shiestapoi** [comment]
![image](https://user-images.githubusercontent.com/118915239/219945705-781c91d3-d10c-43b7-a995-6ad2bae5db6f.png)
