### ISSUE TITLE
leech UPTOBOX error 

### ISSUE THREAD

**Issue by alamia442** [anasty17/mirror-leech-telegram-bot#1415]
2023-03-28T23:14:27.004446+00:00 app[worker.1]: 2023-03-28 23:14:27,001 - asyncio - ERROR - Task exception was never retrieved
2023-03-28T23:14:27.004448+00:00 app[worker.1]: future: <Task finished name='Task-267' coro=<_mirror_leech() done, defined at /app/bot/modules/mirror_leech.py:26> exception=TypeError("unsupported operand type(s) for |=: 'dict' and 'dict'")>
2023-03-28T23:14:27.004452+00:00 app[worker.1]: Traceback (most recent call last):
2023-03-28T23:14:27.004452+00:00 app[worker.1]:   File "/app/bot/modules/mirror_leech.py", line 263, in _mirror_leech
2023-03-28T23:14:27.004454+00:00 app[worker.1]:     await add_aria2c_download(link, path, listener, name, auth, ratio, seed_time)
2023-03-28T23:14:27.004461+00:00 app[worker.1]:   File "/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 175, in add_aria2c_download
2023-03-28T23:14:27.004462+00:00 app[worker.1]:     args |= a2c_opt
2023-03-28T23:14:27.004462+00:00 app[worker.1]: TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

**Comment by anasty17** [comment]
not my docker
