### ISSUE TITLE
Error from cloudscraper import create_scraper

### ISSUE THREAD

**Issue by alamia442** [anasty17/mirror-leech-telegram-bot#1452]
2023-04-27 01:07:18,505 - bot - INFO - Users data has been imported from Database
 Traceback (most recent call last):
   File "/app/.local/lib/python3.8/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
     from requests.packages.urllib3.contrib import appengine as gaecontrib
 ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/app/.local/lib/python3.8/site-packages/urllib3/contrib/__init__.py)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "/app/bot/__main__.py", line 22, in <module>
     from .modules import authorize, clone, gd_count, gd_delete, gd_list, cancel_mirror, mirror_leech, status, torrent_search, torrent_select, ytdlp, rss, shell, eval, users_settings, bot_settings
   File "/app/bot/modules/clone.py", line 19, in <module>
     from bot.helper.mirror_utils.download_utils.direct_link_generator import direct_link_generator
   File "/app/bot/helper/mirror_utils/download_utils/direct_link_generator.py", line 20, in <module>
     from cloudscraper import create_scraper
   File "/app/.local/lib/python3.8/site-packages/cloudscraper/__init__.py", line 10, in <module>
     from requests_toolbelt.utils import dump
   File "/app/.local/lib/python3.8/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
     from .adapters import SSLAdapter, SourceAddressAdapter
   File "/app/.local/lib/python3.8/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
     from .ssl import SSLAdapter
   File "/app/.local/lib/python3.8/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
     from .._compat import poolmanager
   File "/app/.local/lib/python3.8/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
     from urllib3.contrib import appengine as gaecontrib
 ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/app/.local/lib/python3.8/site-packages/urllib3/contrib/__init__.py)

**Comment by alamia442** [comment]
fix by add urllib3==1.26.15 to requirements

**Comment by anasty17** [comment]
Error in u remove this version and just install the missing requirement. U have updated ur bot without installing the new requirement
