### ISSUE TITLE
names error in forwaded meesages 

### ISSUE THREAD

**Issue by satyamisme** [anasty17/mirror-leech-telegram-bot#1518]
just forward messages more than one with bot command 

/qbleech Magneticlin
/qbleech Magneticlin
/qbleech Magneticlin

a%2f%2fnew-line.net%3a6969%2fannounce&tr=udp%3a%2f%2faarsen.me%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.qu.ax%3a6969%2fannounce
2023-08-05 16:59:32,540 - bot - INFO - QbitDownload started: www.5MovieRulz.vc - Kaalkoot (2023) S01 EP (01-08) - HQ HDRip - [Telugu + Tamil + Hindi] - AAC - 1GB - Hash: 768b0bbd84265438b9ccb758ec696d93de9459d6
2023-08-05 16:59:32,585 - bot - INFO - QbitDownload started: www.5MovieRulz.vc - Kaalkoot (2023) S01 EP (01-08) - HQ HDRip - [Telugu + Tamil + Hindi] - AAC - 1GB - Hash: 768b0bbd84265438b9ccb758ec696d93de9459d6
2023-08-05 17:03:29,987 - bot - INFO - Download completed: www.5MovieRulz.vc - Kaalkoot (2023) S01 EP (01-08) - HQ HDRip - [Telugu + Tamil + Hindi] - AAC - 1GB
2023-08-05 17:03:29,993 - bot - INFO - Leech Name: www.5MovieRulz.vc - Slum Dog Husband (2023) 720p Telugu DVDScr x264 MP3 1.2GB.mkv
2023-08-05 17:03:30,112 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2632' coro=<__onDownloadComplete() done, defined at /usr/src/app/bot/helper/listeners/qbit_listener.py:62> exception=AttributeError("'int' object has no attribute 'isdigit'")>
Traceback (most recent call last):
  File "/usr/src/app/bot/helper/listeners/qbit_listener.py", line 76, in __onDownloadComplete
    await listener.onDownloadComplete()
  File "/usr/src/app/bot/helper/listeners/tasks_listener.py", line 316, in onDownloadComplete
    await tg.upload(o_files, m_size, size)
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 177, in upload
    await self.__user_settings()
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 72, in __user_settings
    if not self.__upload_dest.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by anasty17** [comment]
delete the saved data for user in database or use the reset button in usetting. it as int and i have changed it.
