### ISSUE TITLE
[Bug] Starting JDownloader... `httpx.ReadTimeout`

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1650]
**Describe the bug**
Hi,

@anasty17 

I do have same error as [here](https://github.com/anasty17/mirror-leech-telegram-bot/issues/1647) Starting JDownloader, bot won't start now!

OS: buyvm vps LU 2GB Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-135-generic x86_64)

<details>
<summary>log.txt</summary>

```
mltb-app-1  | [2023-12-29 13:12:58 +0000] [49] [INFO] Using worker: gevent
mltb-app-1  | [2023-12-29 13:12:58 +0000] [77] [INFO] Booting worker with pid: 77
mltb-app-1  | 2023-12-29 13:12:58,568 - root - INFO - Creating client from BOT_TOKEN
mltb-app-1  | 2023-12-29 13:13:11,868 - bot - INFO - Users data has been imported from Database
mltb-app-1  | 2023-12-29 13:13:12,160 - bot - INFO - Rss data has been imported from Database.
mltb-app-1  | 2023-12-29 13:13:12,955 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
mltb-app-1  | 2023-12-29 13:13:12,957 - apscheduler.scheduler - INFO - Added job "RSS" to job store "default"
mltb-app-1  | 2023-12-29 13:13:12,958 - apscheduler.scheduler - INFO - Scheduler started
mltb-app-1  | 2023-12-29 13:13:13,072 - bot - INFO - Starting JDownloader... This might take up to 15 sec and might restart once after build!
mltb-app-1  | Traceback (most recent call last):
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
mltb-app-1  |     result = func(*args)
mltb-app-1  |   File "/usr/lib/python3.10/ssl.py", line 917, in read
mltb-app-1  |     v = self._sslobj.read(len)
mltb-app-1  | ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)
mltb-app-1  |
mltb-app-1  | During handling of the above exception, another exception occurred:
mltb-app-1  |
mltb-app-1  | Traceback (most recent call last):
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_core/_tasks.py", line 115, in fail_after
mltb-app-1  |     yield cancel_scope
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/anyio.py", line 34, in read
mltb-app-1  |     return await self._stream.receive(max_bytes=max_bytes)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/streams/tls.py", line 205, in receive
mltb-app-1  |     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
mltb-app-1  |     data = await self.transport_stream.receive()
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 1123, in receive
mltb-app-1  |     await self._protocol.read_event.wait()
mltb-app-1  |   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
mltb-app-1  |     await fut
mltb-app-1  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f5a3ff05a50
mltb-app-1  |
mltb-app-1  | During handling of the above exception, another exception occurred:
mltb-app-1  |
mltb-app-1  | Traceback (most recent call last):
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 10, in map_exceptions
mltb-app-1  |     yield
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/anyio.py", line 32, in read
mltb-app-1  |     with anyio.fail_after(timeout):
mltb-app-1  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
mltb-app-1  |     self.gen.throw(typ, value, traceback)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_core/_tasks.py", line 118, in fail_after
mltb-app-1  |     raise TimeoutError
mltb-app-1  | TimeoutError
mltb-app-1  |
mltb-app-1  | The above exception was the direct cause of the following exception:
mltb-app-1  |
mltb-app-1  | Traceback (most recent call last):
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
mltb-app-1  |     yield
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 371, in handle_async_request
mltb-app-1  |     resp = await self._pool.handle_async_request(req)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
mltb-app-1  |     raise exc
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
mltb-app-1  |     response = await connection.handle_async_request(request)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection.py", line 103, in handle_async_request
mltb-app-1  |     return await self._connection.handle_async_request(request)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 133, in handle_async_request
mltb-app-1  |     raise exc
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 111, in handle_async_request
mltb-app-1  |     ) = await self._receive_response_headers(**kwargs)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
mltb-app-1  |     event = await self._receive_event(timeout=timeout)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 212, in _receive_event
mltb-app-1  |     data = await self._network_stream.read(
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/anyio.py", line 31, in read
mltb-app-1  |     with map_exceptions(exc_map):
mltb-app-1  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
mltb-app-1  |     self.gen.throw(typ, value, traceback)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
mltb-app-1  |     raise to_exc(exc) from exc
mltb-app-1  | httpcore.ReadTimeout
mltb-app-1  |
mltb-app-1  | The above exception was the direct cause of the following exception:
mltb-app-1  |
mltb-app-1  | Traceback (most recent call last):
mltb-app-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
mltb-app-1  |     return _run_code(code, main_globals, None,
mltb-app-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
mltb-app-1  |     exec(code, run_globals)
mltb-app-1  |   File "/usr/src/app/bot/__main__.py", line 279, in <module>
mltb-app-1  |     bot.loop.run_until_complete(main())
mltb-app-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
mltb-app-1  |   File "/usr/src/app/bot/__main__.py", line 238, in main
mltb-app-1  |     await gather(
mltb-app-1  |   File "/usr/src/app/bot/helper/ext_utils/telegraph_helper.py", line 16, in create_account
mltb-app-1  |     await self._telegraph.create_account(
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/telegraph/aio.py", line 106, in create_account
mltb-app-1  |     response = (await self._telegraph.method('createAccount', values={
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/telegraph/aio.py", line 32, in method
mltb-app-1  |     response = (await self.session.post(
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1877, in post
mltb-app-1  |     return await self.request(
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1559, in request
mltb-app-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1646, in send
mltb-app-1  |     response = await self._send_handling_auth(
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1674, in _send_handling_auth
mltb-app-1  |     response = await self._send_handling_redirects(
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1711, in _send_handling_redirects
mltb-app-1  |     response = await self._send_single_request(request)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1748, in _send_single_request
mltb-app-1  |     response = await transport.handle_async_request(request)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 370, in handle_async_request
mltb-app-1  |     with map_httpcore_exceptions():
mltb-app-1  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
mltb-app-1  |     self.gen.throw(typ, value, traceback)
mltb-app-1  |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
mltb-app-1  |     raise mapped_exc(message) from exc
mltb-app-1  | httpx.ReadTimeout
```
</details>

**Comment by anasty17** [comment]
I have no idea ! How to produce this ?

**Comment by erickyun** [comment]
> Is it my docker ?I have no idea ! How to produce this ?

This your docker sir.
I don't understand myself but for me 
this error happend when I executed `/restart` 
and then someitimes jdownloader won't connect! Bot gives infinite `Starting JDownloader...` message until it gives me `httpx.ReadTimeout`

**Comment by anasty17** [comment]
This not happening with me. But I'm Changing how this works now

**Comment by anasty17** [comment]
someone got same problem then he siad it fixed so issue from ur side 
make fresh build
