### ISSUE TITLE
Bug error when leech/mirror telegram files "AttributeError: 'str' object has no attribute 'session'"

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1673]
**Describe the bug**
hi anas,

When I execute /l or /m on telegram file bot throw error on logs and bot won't download/upload file?

<details>
<summary>log.txt</summary>

```
2024-01-29 11:17:12,155 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1643' coro=<Mirror.newEvent() done, defined at /usr/src/app/bot/modules/mirror_leech.py:71> exception=AttributeError("'str' object has no attribute 'session'")>
Traceback (most recent call last):
  File "/usr/src/app/bot/modules/mirror_leech.py", line 303, in newEvent
    await TelegramDownloadHelper(self).add_download(reply_to, f"{path}/", session)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_download.py", line 98, in add_download
    self.session.session = "user"
AttributeError: 'str' object has no attribute 'session'
```
</details>

**Comment by anasty17** [comment]
Fixed
