### ISSUE TITLE
ModuleNotFoundError: No module named 'asgiref'

### ISSUE THREAD

**Issue by iamMJ8384** [anasty17/mirror-leech-telegram-bot#267]
**Full bot Log:** 

2022-01-10T08:30:01.400859+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-01-10T08:30:04.806759+00:00 app[web.1]: warning: no common commits
2022-01-10T08:30:06.444104+00:00 heroku[web.1]: State changed from starting to up
2022-01-10T08:30:06.265671+00:00 app[web.1]: [2022-01-10 08:30:06 +0000] [31] [INFO] Starting gunicorn 20.1.0
2022-01-10T08:30:06.266159+00:00 app[web.1]: [2022-01-10 08:30:06 +0000] [31] [INFO] Listening at: http://0.0.0.0:52314 (31)
2022-01-10T08:30:06.266218+00:00 app[web.1]: [2022-01-10 08:30:06 +0000] [31] [INFO] Using worker: aiohttp.GunicornWebWorker
2022-01-10T08:30:06.269943+00:00 app[web.1]: [2022-01-10 08:30:06 +0000] [59] [INFO] Booting worker with pid: 59
2022-01-10T08:30:07.063505+00:00 app[web.1]: 2022-01-10 08:30:07,063 - bot - INFO - Generating BOT_STRING_SESSION
2022-01-10T08:30:07.064883+00:00 app[web.1]: 2022-01-10 08:30:07,064 - root - INFO - Initializing Aria2c
2022-01-10T08:30:08.127664+00:00 heroku[router]: at=info method=GET path="/" host=mjmirror8384.herokuapp.com request_id=3d92367e-c328-462c-9646-7ecbdecf4091 fwd="54.146.147.54" dyno=web.1 connect=0ms service=1ms status=200 bytes=338 protocol=https
2022-01-10T08:30:08.645766+00:00 app[web.1]: 2022-01-10 08:30:08,645 - bot - INFO - Creating TELEGRAPH Account using  'SgBCmvbb' name
2022-01-10T08:30:10.098521+00:00 app[web.1]: Traceback (most recent call last):
2022-01-10T08:30:10.098537+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-10T08:30:10.099890+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-01-10T08:30:10.099903+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-10T08:30:10.100445+00:00 app[web.1]:     exec(code, run_globals)
2022-01-10T08:30:10.100507+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 22, in <module>
2022-01-10T08:30:10.101216+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, speedtest, count, leech_settings, search, rss
2022-01-10T08:30:10.101294+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 31, in <module>
2022-01-10T08:30:10.101905+00:00 app[web.1]:     from bot.helper.mirror_utils.upload_utils import gdriveTools, pyrogramEngine
2022-01-10T08:30:10.101916+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 10, in <module>
2022-01-10T08:30:10.102203+00:00 app[web.1]:     from asgiref.sync import async_to_sync
2022-01-10T08:30:10.102275+00:00 app[web.1]: ModuleNotFoundError: No module named 'asgiref'

**Comment by prono69** [comment]
Happend with me too

**Comment by xd003** [comment]
That is happening because the latest commit needs a redeploy . Your bot has pulled up the latest commit at dyno restart but since requirements was modified which happpens only during deploying stage , it is reporting the missing module . Simply redeploy the app with latest commit

**Comment by iamMJ8384** [comment]
> That is happening because the latest commit needs a redeploy . Your bot has pulled up the latest commit at dyno restart but since requirements was modified which happpens only during deploying stage , it is reporting the missing module . Simply redeploy the app with latest commit

Thx worked

**Comment by NskTorrent** [comment]
> That is happening because the latest commit needs a redeploy . Your bot has pulled up the latest commit at dyno restart but since requirements was modified which happpens only during deploying stage , it is reporting the missing module . Simply redeploy the app with latest commit

Hello! I'm sorry to bother you, but I'm quite a beginner. How can I apply the latest commits? Could you please give step by step instructions. The search did not help (
Thank you in advance for your help.

**Comment by prono69** [comment]
@NskTorrent u have to re-deploy . Deploy again as u did to deploy the bot at first time .

**Comment by NskTorrent** [comment]
Actions -> Manually Deploy to Heroku -> Run Workflow -> Branch: heroku.

After deploying nothing changes. The heroku log is the same:
2022-01-11T05: 33: 57.281466 + 00: 00 app [web.1]: from asgiref.sync import async_to_sync
2022-01-11T05: 33: 57.281506 + 00: 00 app [web.1]: ModuleNotFoundError: No module named 'asgiref'

I think I am missing the step where I need to apply the latest updates to the owner of the code.
But I don’t know how to do it.

**Comment by iamMJ8384** [comment]
> Actions -> Manually Deploy to Heroku -> Run Workflow -> Branch: heroku.
> 
> After deploying nothing changes. The heroku log is the same: 2022-01-11T05: 33: 57.281466 + 00: 00 app [web.1]: from asgiref.sync import async_to_sync 2022-01-11T05: 33: 57.281506 + 00: 00 app [web.1]: ModuleNotFoundError: No module named 'asgiref'
> 
> I think I am missing the step where I need to apply the latest updates to the owner of the code. But I don’t know how to do it.

You'll need to update 2 files: 
1st: requirements.txt in heroku branch
2nd: bot/helper/mirror_utils/upload_utils/gdriveTools.py in master branch

Then redeploy the bot

**Comment by NskTorrent** [comment]
@iamMJ8384 Thanks for the detailed answer! Is there a tool on Github to do this automatically? Or do I need to manually download these files from the owner's repository and manually upload them to my repository?
