### ISSUE TITLE
Bot error 

### ISSUE THREAD

**Issue by gosndka** [anasty17/mirror-leech-telegram-bot#273]
2022-01-11T09:51:48.607469+00:00 app[web.1]: Traceback (most recent call last):

2022-01-11T09:51:48.607482+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

2022-01-11T09:51:48.607607+00:00 app[web.1]:     return _run_code(code, main_globals, None,

2022-01-11T09:51:48.607618+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

2022-01-11T09:51:48.607700+00:00 app[web.1]:     exec(code, run_globals)

2022-01-11T09:51:48.607709+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 22, in <module>

2022-01-11T09:51:48.607796+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, speedtest, count, leech_settings, search, rss

2022-01-11T09:51:48.607798+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 31, in <module>

2022-01-11T09:51:48.607864+00:00 app[web.1]:     from bot.helper.mirror_utils.upload_utils import gdriveTools, pyrogramEngine

2022-01-11T09:51:48.607881+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 10, in <module>

2022-01-11T09:51:48.607942+00:00 app[web.1]:     from asgiref.sync import async_to_sync

2022-01-11T09:51:48.607976+00:00 app[web.1]: ModuleNotFoundError: No module named 'asgiref'

**Comment by gosndka** [comment]
@anasty17 why was the repo closed? I had deployed the bot on dec and it working well but now it shows this error and I want to know why this happened

**Comment by anasty17** [comment]
Read commits title

**Comment by gosndka** [comment]
> Read commits title

so the bot fetchs the new repo everytime it restarts or it uses the old repo the one which I used for deploying?  @anasty17
