### ISSUE TITLE
Having problem after deployment of bot

### ISSUE THREAD

**Issue by DXDDEVIL** [anasty17/mirror-leech-telegram-bot#382]
ModuleNotFoundError: No module named 'bencoding

Showing this error in heroku log

**Comment by snehitap** [comment]
@DXDDEVIL Nice, very nice.

**Comment by HiroyukiKiyoshi** [comment]
Same problem

```
2022-02-09T03:03:02.340410+00:00 app[web.1]: Traceback (most recent call last):
2022-02-09T03:03:02.340417+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-02-09T03:03:02.340418+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-02-09T03:03:02.340418+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-02-09T03:03:02.340419+00:00 app[web.1]:     exec(code, run_globals)
2022-02-09T03:03:02.340419+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 22, in <module>
2022-02-09T03:03:02.340425+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, speedtest, count, leech_settings, search, rss
2022-02-09T03:03:02.340426+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 24, in <module>
2022-02-09T03:03:02.340426+00:00 app[web.1]:     from bot.helper.mirror_utils.download_utils.qbit_downloader import add_qb_torrent
2022-02-09T03:03:02.340427+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/qbit_downloader.py", line 2, in <module>
2022-02-09T03:03:02.340427+00:00 app[web.1]:     from bencoding import bencode, bdecode
2022-02-09T03:03:02.340428+00:00 app[web.1]: ModuleNotFoundError: No module named 'bencoding'
```

**Comment by govindms777** [comment]
Me too

**Comment by moi662** [comment]
Me too

**Comment by bottt777** [comment]
> Yo también

Hello, I have the same error.
some solution?

**Comment by moi662** [comment]
> > Yo también
> 
> Hello, I have the same error. some solution?



> > Yo también
> 
> Hello, I have the same error. some solution?

Redeploy

**Comment by govindms777** [comment]
I'm still getting the issue even after redeploy

**Comment by Strangelets** [comment]
delete forked repo & fork again create new secrets

and deploy

**Comment by anasty17** [comment]
Before deploying u need to fetch and merge... and don't rerun old workflow

**Comment by cyberfro** [comment]
I created mirror bot first time ever
But it won't work 😥

**Comment by anasty17** [comment]
> I created mirror bot first time ever But it won't work 😥

Sure it will not, what did u expect ?
