### ISSUE TITLE
ModuleNotFoundError: No module named 'bencoding'

### ISSUE THREAD

**Issue by FilmBee** [anasty17/mirror-leech-telegram-bot#384]
Application Logs
2022-02-09T04:33:44.845701+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 22, in <module>
2022-02-09T04:33:44.845702+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, speedtest, count, leech_settings, search, rss
2022-02-09T04:33:44.845702+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 24, in <module>
2022-02-09T04:33:44.845704+00:00 app[web.1]:     from bot.helper.mirror_utils.download_utils.qbit_downloader import add_qb_torrent
2022-02-09T04:33:44.845704+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/qbit_downloader.py", line 2, in <module>
2022-02-09T04:33:44.845705+00:00 app[web.1]:     from bencoding import bencode, bdecode
2022-02-09T04:33:44.845705+00:00 app[web.1]: ModuleNotFoundError: No module named 'bencoding'
2022-02-09T04:33:45.098656+00:00 app[web.1]: [2022-02-09 04:33:45 +0000] [31] [ERROR] Connection in use: ('0.0.0.0', 51062)
2022-02-09T04:33:45.098690+00:00 app[web.1]: [2022-02-09 04:33:45 +0000] [31] [ERROR] Retrying in 1 second.
2022-02-09T04:33:46.099961+00:00 app[web.1]: [2022-02-09 04:33:46 +0000] [31] [ERROR] Can't connect to ('0.0.0.0', 51062)
2022-02-09T04:34:36.854811+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2022-02-09T04:34:36.886478+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-02-09T04:34:37.139753+00:00 heroku[web.1]: State changed from starting to crashed
2022-02-09T04:34:37.151106+00:00 heroku[web.1]: State changed from crashed to starting
2022-02-09T04:34:37.024436+00:00 heroku[web.1]: Process exited with status 137
2022-02-09T04:34:55.866760+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=bdmovie6999.herokuapp.com request_id=2b45336b-8dbf-4b4e-a088-cafcd4a8ec04 fwd="52.31.47.33" dyno= connect= service= status=503 bytes= protocol=https
2022-02-09T04:35:06.475222+00:00 app[web.1]: warning: no common commits
2022-02-09T04:35:05.207904+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-02-09T04:35:08.102584+00:00 heroku[web.1]: State changed from starting to up
2022-02-09T04:35:07.934577+00:00 app[web.1]: [2022-02-09 04:35:07 +0000] [31] [INFO] Starting gunicorn 20.1.0
2022-02-09T04:35:07.934943+00:00 app[web.1]: [2022-02-09 04:35:07 +0000] [31] [INFO] Listening at: http://0.0.0.0:8847 (31)
2022-02-09T04:35:07.934995+00:00 app[web.1]: [2022-02-09 04:35:07 +0000] [31] [INFO] Using worker: aiohttp.GunicornWebWorker
2022-02-09T04:35:07.939214+00:00 app[web.1]: [2022-02-09 04:35:07 +0000] [60] [INFO] Booting worker with pid: 60
2022-02-09T04:35:08.798447+00:00 app[web.1]: 2022-02-09 04:35:08,798 - bot - INFO - Generating BOT_STRING_SESSION
2022-02-09T04:35:09.800422+00:00 app[web.1]: 2022-02-09 04:35:09,800 - root - INFO - Initializing Aria2c
2022-02-09T04:35:09.792679+00:00 heroku[router]: at=info method=GET path="/" host=bdmovie6999.herokuapp.com request_id=fe2dd82a-7fbc-461d-8a7c-0b9468d3afe2 fwd="3.250.45.0" dyno=web.1 connect=0ms service=1ms status=200 bytes=338 protocol=https
2022-02-09T04:35:11.671586+00:00 app[web.1]: 2022-02-09 04:35:11,671 - bot - INFO - Creating TELEGRAPH Account using  'Lmqtxepe' name
2022-02-09T04:35:11.881312+00:00 app[web.1]: Traceback (most recent call last):
2022-02-09T04:35:11.881316+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-02-09T04:35:11.881316+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-02-09T04:35:11.881316+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-02-09T04:35:11.881317+00:00 app[web.1]:     exec(code, run_globals)
2022-02-09T04:35:11.881317+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 22, in <module>
2022-02-09T04:35:11.881331+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, speedtest, count, leech_settings, search, rss
2022-02-09T04:35:11.881331+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 24, in <module>
2022-02-09T04:35:11.881331+00:00 app[web.1]:     from bot.helper.mirror_utils.download_utils.qbit_downloader import add_qb_torrent
2022-02-09T04:35:11.881332+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/qbit_downloader.py", line 2, in <module>
2022-02-09T04:35:11.881333+00:00 app[web.1]:     from bencoding import bencode, bdecode
2022-02-09T04:35:11.881333+00:00 app[web.1]: ModuleNotFoundError: No module named 'bencoding'

**Comment by yadianluffy** [comment]
not to ask any more questions about the new update here is the solution 
![Captura de pantalla (27)](https://user-images.githubusercontent.com/88897873/153124795-1a012c05-38d5-4d9a-bf0c-dba5c44b9645.png)
![Captura de pantalla (28)](https://user-images.githubusercontent.com/88897873/153125127-cc727583-409d-455f-a309-af8891d47aac.png)


and then deploy again and problem solved.

**Comment by traviss64** [comment]
> solved

Not working :(

**Comment by FilmBee** [comment]
> 

Thank you problem solved

**Comment by traviss64** [comment]
> > 
> 
> Thank you problem solved

what exactly you did?I did the same procedure thrice now and I am getting the same error

**Comment by Strangelets** [comment]
delete forked repo & fork again create new secrets 

and deploy

**Comment by David-Shadow** [comment]
I think maybe this is because anas didn't update the requirements.txt in heroku branch...and you're all deploying with heroku branch...so..try updating requirements.txt in heroku branch with the main branch then redeploy 🧑‍🦯

**Comment by David-Shadow** [comment]
This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯

**Comment by lckeong** [comment]
> not to ask any more questions about the new update here is the solution ![Captura de pantalla (27)](https://user-images.githubusercontent.com/88897873/153124795-1a012c05-38d5-4d9a-bf0c-dba5c44b9645.png) ![Captura de pantalla (28)](https://user-images.githubusercontent.com/88897873/153125127-cc727583-409d-455f-a309-af8891d47aac.png)
> 
> and then deploy again and problem solved.

still not work

**Comment by traviss64** [comment]
> This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯

How to do that?

**Comment by lckeong** [comment]
> This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯

eleborate please

**Comment by David-Shadow** [comment]
> > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> 
> How to do that?

First click here to change the branch to heroku
![IMG_20220209_115736_867](https://user-images.githubusercontent.com/92687730/153134794-760fc18c-4211-4fa5-846b-2acb5f5f3d37.jpg)

Then click here to fetch n merge
![IMG_20220209_120031_909](https://user-images.githubusercontent.com/92687730/153134830-2e56f1c2-5bd9-4991-9c0f-4e95c8a51612.jpg)

Then run Workflow on heroku branch

**Comment by David-Shadow** [comment]
> > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> 
> eleborate please
Answered here 
https://github.com/anasty17/mirror-leech-telegram-bot/issues/384#issuecomment-1033399084

**Comment by lckeong** [comment]
> > > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> > 
> > 
> > eleborate please
> > Answered here
> > [#384 (comment)](https://github.com/anasty17/mirror-leech-telegram-bot/issues/384#issuecomment-1033399084)

that for fork repo right?what about import repo

**Comment by David-Shadow** [comment]
> > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> 
> eleborate please
Answered here 
https://github.com/anasty17/mirror-leech-telegram-bot/issues/384#issuecomment-1033399084

> > > > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> > > 
> > > 
> > > eleborate please
> > > Answered here
> > > [#384 (comment)](https://github.com/anasty17/mirror-leech-telegram-bot/issues/384#issuecomment-1033399084)
> 
> that for fork repo right?what about import repo

Why import🙄🙄...
(For imported repo you can just copy the requirements.txt of official repo and edit in heroku branch of your own repo...rest idk🥱 why even import it 🤷‍♂ you won't recieve regular updates🤷‍♂)

**Comment by seman01** [comment]
> > > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> > 
> > 
> > eleborate please
> > Answered here
> > [#384 (comment)](https://github.com/anasty17/mirror-leech-telegram-bot/issues/384#issuecomment-1033399084)
> 
> > > > > This is because you're not updating the heroku branch...and you're all deploying with heroku branch...so..try fetch-n-merge heroku branch then redeploy 🧑‍🦯
> > > > 
> > > > 
> > > > eleborate please
> > > > Answered here
> > > > [#384 (comment)](https://github.com/anasty17/mirror-leech-telegram-bot/issues/384#issuecomment-1033399084)
> > 
> > 
> > that for fork repo right?what about import repo
> 
> Why import🙄🙄... (For imported repo you can just copy the requirements.txt of official repo and edit in heroku branch of your own repo...rest idk🥱 why even import it 🤷‍♂ you won't recieve regular updates🤷‍♂)

most people follow youtube,if i dont receive regular update,why my bot still got problem after main repo changes?it suppose to work if i dont touch it

**Comment by 0ibaba** [comment]
@seman01 If you imported it, and you have the upstream repo var set to the main repo, it'll obviously cause problems.
Change it to your imported repo's url if you don't update regularly.

**Comment by seman01** [comment]
> @seman01 If you imported it, and you have the upstream repo var set to the main repo, it'll obviously cause problems. Change it to your imported repo's url if you don't update regularly.

thank for the tip,no wonder got problem. so how i can manually update if i want it?just redeploy?

**Comment by anasty17** [comment]
Before deploying u need to fetch and merge... and don't rerun old workflow
