### ISSUE TITLE
problem starting the bot

### ISSUE THREAD

**Issue by DevilStyle** [anasty17/mirror-leech-telegram-bot#441]
Hi, congratulations for the work you do, I have set all the parameters in the config.env file but when I try to start the bot it keeps giving me these errors, how can I fix? A thousand thanks

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/mirror-leech-telegram-bot/bot/__main__.py", line 20, in <module>
    from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, speedtest, count, leech_settings, search, rss
  File "/home/user/mirror-leech-telegram-bot/bot/modules/mirror.py", line 23, in <module>
    from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download
  File "/home/user/mirror-leech-telegram-bot/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 6, in <module>
    from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
ImportError: cannot import name 'MegaApi' from 'mega' (unknown location)

**Comment by anasty17** [comment]
Follow readme and don't edit the code

**Comment by DevilStyle** [comment]
I have not changed any code, I have performed all the steps that are written there but it keeps giving those errors without starting. How can I solve? Thank you
