### ISSUE TITLE
mega erro

### ISSUE THREAD

**Issue by nimdinu** [anasty17/mirror-leech-telegram-bot#523]
2022-04-27T05:12:29.849865+00:00 app[web.1]:     from megasdkrestclient import MegaSdkRestClient, errors as mega_err
2022-04-27T05:12:29.849865+00:00 app[web.1]: ModuleNotFoundError: No module named 'megasdkrestclient'

i deployed this app to heroku. i don't add g drive or mega .. at the first time it works perfectly... but some days later it began to crash with this error message....    can you please help me

**Comment by AwayJob** [comment]
```
2022-04-27T05:06:13.949853+00:00 app[web.1]: warning: no common commits
2022-04-27T05:06:14.131398+00:00 app[web.1]: 2022-04-27 05:06:14,131 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-04-27T05:06:15.118239+00:00 app[web.1]: Traceback (most recent call last):
2022-04-27T05:06:15.118268+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2022-04-27T05:06:15.118268+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-04-27T05:06:15.118268+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2022-04-27T05:06:15.118269+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-04-27T05:06:15.118269+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2022-04-27T05:06:15.118270+00:00 app[web.1]:     __import__(pkg_name)
2022-04-27T05:06:15.118271+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 15, in <module>
2022-04-27T05:06:15.118271+00:00 app[web.1]:     from megasdkrestclient import MegaSdkRestClient, errors as mega_err
2022-04-27T05:06:15.118271+00:00 app[web.1]: ModuleNotFoundError: No module named 'megasdkrestclient'
```
same

**Comment by Arpiakash** [comment]
Redeploy

**Comment by anasty17** [comment]
Cz no one read heroku branch readme take ur time with reading new updates pushed..
