### ISSUE TITLE
Cannot leech anything. other things are working properly.

### ISSUE THREAD

**Issue by Kryptoneer** [anasty17/mirror-leech-telegram-bot#537]
logError --->  AttributeError: 'Message' object has no attribute 'message_id'

This error shows in the logs. /leechwatch , /leech , /zipleech , /unzipleech commands are not working. Thank you.

complete log ->

2022-04-29T23:57:46.618499+00:00 app[web.1]: 2022-04-29 23:57:46,618 - bot - INFO - Download completed: 1- What is Python.mp4
2022-04-29T23:57:46.621760+00:00 app[web.1]: 2022-04-29 23:57:46,621 - bot - INFO - Leech Name: 1- What is Python.mp4
2022-04-29T23:58:03.264103+00:00 app[web.1]: 2022-04-29 23:58:03,263 - bot.helper.mirror_utils.upload_utils.pyrogramEngine - ERROR - Invalid parse mode "html" File: /usr/src/app/downloads/493/1- What is Python.mp4
2022-04-29T23:58:03.278189+00:00 app[web.1]: Exception in thread Thread-11:
2022-04-29T23:58:03.278200+00:00 app[web.1]: Traceback (most recent call last):
2022-04-29T23:58:03.278237+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-04-29T23:58:03.278504+00:00 app[web.1]:     self.run()
2022-04-29T23:58:03.278514+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2022-04-29T23:58:03.278681+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2022-04-29T23:58:03.278701+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 160, in onDownloadComplete
2022-04-29T23:58:03.278817+00:00 app[web.1]:     tg.upload()
2022-04-29T23:58:03.278830+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 56, in upload
2022-04-29T23:58:03.278926+00:00 app[web.1]:     self.__msgs_dict[file_] = self.__sent_msg.message_id
2022-04-29T23:58:03.278963+00:00 app[web.1]: AttributeError: 'Message' object has no attribute 'message_id'
2022-04-29T23:58:20.596266+00:00 app[web.1]: 2022-04-29 23:58:20,595 - bot.helper.mirror_utils.upload_utils.pyrogramEngine - INFO - Cancelling Upload: 1- What is Python.mp4

**Comment by anasty17** [comment]
Update ure repo and deploy again
