### ISSUE TITLE
Error running docker container

### ISSUE THREAD

**Issue by NandiyaLive** [anasty17/mirror-leech-telegram-bot#538]
I get this error wen try to run `sudo docker run -p 80:80 mirror-bot`

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 15, in <module>
    from wserver import start_server_async
ModuleNotFoundError: No module named 'wserver'
```

**Comment by anasty17** [comment]
Update ur repo

**Comment by NandiyaLive** [comment]
I'm using your repo
