### ISSUE TITLE
Getting error at canceling tg files download

### ISSUE THREAD

**Issue by xor69** [anasty17/mirror-leech-telegram-bot#548]
bot - INFO - Cancelling download on user request: BQACAgUAAxkBAAIDlWJxhvmo5HkyZs2lIYyAc9jTnpI_AAKpBQAC9Ld5Vg69K-HgQ
Exception in thread Thread-14 (__download):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 83, in __download
    self.__onDownloadComplete()
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 70, in __onDownloadComplete
    GLOBAL_GID.remove(self.__id)
KeyError: 'BQACAgUAAxkBAAIDlWJxhvmo5HkyZs2lIYyAc9jTnpI_AAKpBQAC9Ld5Vg69K-HgQ'

**Comment by anasty17** [comment]
Yeah i know this issue. I habe reported a bug for pyrogram . Waiting till reply. But this error will not effect anything.

**Comment by anasty17** [comment]
Fixed check pyrogram last commit version 4.0.17
