### ISSUE TITLE
Stop duplicate not working

### ISSUE THREAD

**Issue by alok99-git** [anasty17/mirror-leech-telegram-bot#56]
Log :

```
app[web.1]: 2021-11-24 08:01:24,620 - bot - INFO - https://api.droidontime.com/api/download/rosy/v5.2.1/vanilla
2021-11-24T08:01:24.621100+00:00 app[web.1]: 2021-11-24 08:01:24,620 - bot - INFO - No Direct link function found for https://api.droidontime.com/api/download/rosy/v5.2.1/vanilla
2021-11-24T08:01:24.632913+00:00 app[web.1]: 2021-11-24 08:01:24,632 - bot - INFO - Started: e85ad84c573ac7fb DIR:/usr/src/app/downloads/124 
2021-11-24T08:01:25.640769+00:00 app[web.1]: 2021-11-24 08:01:25,640 - bot - INFO - Checking File/Folder if already in Drive...
2021-11-24T08:01:26.154293+00:00 app[web.1]: Exception in thread Thread-14:
2021-11-24T08:01:26.154305+00:00 app[web.1]: Traceback (most recent call last):
2021-11-24T08:01:26.154306+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-11-24T08:01:26.155406+00:00 app[web.1]:     self.run()
2021-11-24T08:01:26.155420+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-11-24T08:01:26.155612+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2021-11-24T08:01:26.155626+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 28, in __onDownloadStarted
2021-11-24T08:01:26.155713+00:00 app[web.1]:     smsg, button = gdrive.drive_list(sname, True)
2021-11-24T08:01:26.155726+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 747, in drive_list
2021-11-24T08:01:26.155985+00:00 app[web.1]:     for n in self.get_recursive_list(file, parent_id)
2021-11-24T08:01:26.155998+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 602, in get_recursive_list
2021-11-24T08:01:26.156190+00:00 app[web.1]:     fileId=file.get("parents")[0],
2021-11-24T08:01:26.156229+00:00 app[web.1]: TypeError: 'NoneType' object is not subscriptable
```

**Comment by anasty17** [comment]
@alok99-git Fixed try now

**Comment by anasty17** [comment]
@alok99-git If using heroku branch without upstream repo just do /restart

**Comment by anasty17** [comment]
@alok99-git U added folder id right ? I mean upload destination

**Comment by alok99-git** [comment]
> @alok99-git U added folder id right ? I mean upload destination

Yes

**Comment by alok99-git** [comment]
Now working, thanks
