### ISSUE TITLE
ModuleNotFoundError: No module named 'mega'

### ISSUE THREAD

**Issue by kanekabkz** [anasty17/mirror-leech-telegram-bot#583]
```
app_1  | 2022-05-15 10:22:41,690 - bot - INFO - Generating BOT_STRING_SESSION
app_1  | 2022-05-15 10:22:41,692 - root - INFO - Initializing Aria2c
app_1  | 2022-05-15 10:22:43,194 - root - WARNING - MEGA API KEY not provided!
app_1  | 2022-05-15 10:22:43,194 - root - WARNING - MEGA Credentials not provided!
app_1  | 2022-05-15 10:22:43,528 - bot - INFO - Creating TELEGRAPH Account using  'JjHuuJjr' name
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
app_1  |     return _run_code(code, main_globals, None,
app_1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
app_1  |     exec(code, run_globals)
app_1  |   File "/usr/src/app/bot/__main__.py", line 21, in <module>
app_1  |     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, count, leech_settings, search, rss
app_1  |   File "/usr/src/app/bot/modules/mirror.py", line 24, in <module>
app_1  |     from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 5, in <module>
app_1  |     from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
app_1  | ModuleNotFoundError: No module named 'mega'
```

im geting this error when im trying to deploy my vds

**Comment by kanekabkz** [comment]
@anasty17 I installed it with "pip install mega" but this time it gave an error like this.

```
app_1  | 2022-05-15 10:48:53,373 - bot - INFO - Generating BOT_STRING_SESSION
app_1  | 2022-05-15 10:48:53,374 - root - INFO - Initializing Aria2c
app_1  | 2022-05-15 10:48:54,876 - root - WARNING - MEGA API KEY not provided!
app_1  | 2022-05-15 10:48:54,876 - root - WARNING - MEGA Credentials not provided!
app_1  | 2022-05-15 10:48:55,172 - bot - INFO - Creating TELEGRAPH Account using  'aOnRDKkj' name
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
app_1  |     return _run_code(code, main_globals, None,
app_1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
app_1  |     exec(code, run_globals)
app_1  |   File "/usr/src/app/bot/__main__.py", line 21, in <module>
app_1  |     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, count, leech_settings, search, rss
app_1  |   File "/usr/src/app/bot/modules/mirror.py", line 24, in <module>
app_1  |     from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 5, in <module>
app_1  |     from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
app_1  | ImportError: cannot import name 'MegaApi' from 'mega' (/usr/local/lib/python3.10/dist-packages/mega/__init__.py)
```

**Comment by kanekabkz** [comment]
I closed auto update and deleted this command line and started working. but mega not working. 

mirror-leech-telegram-bot/tree/master/bot/modules)/mirror.py

from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download

if you fix mega, can you mention me? @anasty17

**Comment by erickyun** [comment]
@kanekabkz 

Did you find any fix? I'm having the same problem.

**Comment by kanekabkz** [comment]
You have to fork again and deploy again.

**Comment by erickyun** [comment]
> You have to fork again and deploy again.

Fork and deploy again doesn't work for me because

I'm trying to deploy this bot on mine android phone. And because of that I can't use dockerfile so I have to download Dependencies manually.

@anasty17 or @kanekabkz İf you could tell me ehat Dependencies I need for mega.nz I would really appreciate it?
