### ISSUE TITLE
Racaty.net download error

### ISSUE THREAD

**Issue by pachax001** [anasty17/mirror-leech-telegram-bot#596]
Cannot download from racaty.net links.Bot is hosted on oracle.In log get thia error.
2022-05-19 14:54:39,718 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-05-19 14:54:42,189 - bot - INFO - Generating BOT_STRING_SESSION
2022-05-19 14:54:42,198 - root - INFO - Initializing Aria2c
2022-05-19 14:54:43,700 - root - WARNING - MEGA API KEY not provided!
2022-05-19 14:54:43,701 - root - WARNING - MEGA Credentials not provided!
2022-05-19 14:54:43,701 - root - WARNING - BASE_URL_OF_BOT not provided!
2022-05-19 14:54:44,539 - bot - INFO - Creating TELEGRAPH Account using  'cqftJVtn' name
2022-05-19 14:54:51,603 - apscheduler.scheduler - INFO - Scheduler started
2022-05-19 14:54:51,736 - bot - INFO - Bot Started!
2022-05-19 14:55:01,642 - bot - INFO - https://racaty.net/u2uaor13ultd
2022-05-19 14:55:02,173 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/mirror.py", line 434, in mirror
    _mirror(context.bot, update.message)
  File "/usr/src/app/bot/modules/mirror.py", line 382, in _mirror
    link = direct_link_generator(link)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/direct_link_generator.py", line 63, in direct_link_generator
    return racaty(link)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/direct_link_generator.py", line 250, in racaty
    r = scraper.get(url)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cfscrape/__init__.py", line 121, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Anyway to fix this.

**Comment by junedkh** [comment]
![image](https://user-images.githubusercontent.com/9571025/169782741-5e05cc71-304e-4189-b1f7-e7222a9ca126.png)

This is working fine the problem is from your host
