### ISSUE TITLE
ImportError: cannot import name 'MegaApi' from 'mega' 

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#601]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/home/test-mirror/bot/__main__.py", line 21, in <module>
    from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, count, leech_settings, search, rss
  File "/data/data/com.termux/files/home/test-mirror/bot/modules/mirror.py", line 24, in <module>
    from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download
  File "/data/data/com.termux/files/home/test-mirror/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 5, in <module>
    from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
ImportError: cannot import name 'MegaApi' from 'mega' (/usr/local/lib/python3.9/dist-packages/mega/__init__.py)
```

I deployed using these command without docker from previous repo.

 am I missing some Dependencies? Why am I receving this error could you help me please?

```
apt-get -y update && DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y python3 python3-pip aria2 qbittorrent-nox \
    tzdata p7zip-full p7zip-rar xz-utils curl pv jq ffmpeg \
    locales git unzip rtmpdump libmagic-dev libcurl4-openssl-dev \
    libssl-dev libc-ares-dev libsodium-dev libcrypto++-dev \
    libsqlite3-dev libfreeimage-dev libpq-dev libffi-dev \
    && locale-gen en_US.UTF-8 && \
    curl -L https://github.com/anasty17/megasdkrest/releases/download/latest/megasdkrest-$(cpu=$(uname -m);\
    if [[ "$cpu" == "x86_64" ]]; then echo "amd64"; elif [[ "$cpu" == "x86" ]]; \
    then echo "i386"; elif [[ "$cpu" == "aarch64" ]]; then echo "arm64"; else echo $cpu; fi) \
    -o /usr/local/bin/megasdkrest && chmod +x /usr/local/bin/megasdkrest
```

```
pip3 install --no-cache-dir -r requirements.txt
```

```
pip install mega.py
```

**Comment by erickyun** [comment]
@anasty17 

I'm trying to deploy this on android termux so I cant use the dockerfile thats why I'm asking? So Could you please tell me what Dependencies I need for mega.nz?

**Comment by Team-Infamous** [comment]
how to fix it

**Comment by anasty17** [comment]
> how to fix it

Mega adk remove since 2023
Now we r using jdownloader
