### ISSUE TITLE
heroku logs

### ISSUE THREAD

**Issue by Hikkahujur** [anasty17/mirror-leech-telegram-bot#666]
2022-06-06T12:59:24.157073+00:00 app[web.1]: 2022-06-06 12:59:24,156 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-06-06T12:59:25.060159+00:00 app[web.1]: Traceback (most recent call last):
2022-06-06T12:59:25.060182+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-06-06T12:59:25.060261+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-06-06T12:59:25.060263+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-06-06T12:59:25.060333+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-06-06T12:59:25.060335+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-06-06T12:59:25.060415+00:00 app[web.1]:     __import__(pkg_name)
2022-06-06T12:59:25.060417+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 59, in <module>
2022-06-06T12:59:25.060480+00:00 app[web.1]:     srun(["qbittorrent-nox", "-d", "--profile=."])
2022-06-06T12:59:25.060482+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-06-06T12:59:25.060600+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-06-06T12:59:25.060602+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-06-06T12:59:25.060765+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-06-06T12:59:25.060767+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-06-06T12:59:25.061023+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-06-06T12:59:25.061034+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-06-06T12:59:25.332169+00:00 heroku[web.1]: Process exited with status 1
2022-06-06T12:59:25.475021+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by anasty17** [comment]
Deploy heroku branch not master
