### ISSUE TITLE
Receiving error after deploying Heroku branch 

### ISSUE THREAD

**Issue by anny414** [anasty17/mirror-leech-telegram-bot#672]
Gating this error

```
2022-06-07T06:40:21.687142+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-06-07T06:40:23.526147+00:00 app[web.1]: 2022-06-07 06:40:23,525 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-06-07T06:40:24.852545+00:00 heroku[web.1]: Process exited with status 1
2022-06-07T06:40:24.545048+00:00 app[web.1]: Traceback (most recent call last):
2022-06-07T06:40:24.545077+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-06-07T06:40:24.545174+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-06-07T06:40:24.545183+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-06-07T06:40:24.545268+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-06-07T06:40:24.545276+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-06-07T06:40:24.545348+00:00 app[web.1]:     __import__(pkg_name)
2022-06-07T06:40:24.545357+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 59, in <module>
2022-06-07T06:40:24.545428+00:00 app[web.1]:     srun(["qbittorrent-nox", "-d", "--profile=."])
2022-06-07T06:40:24.545436+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-06-07T06:40:24.545571+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-06-07T06:40:24.545579+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-06-07T06:40:24.545757+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-06-07T06:40:24.545765+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-06-07T06:40:24.546057+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-06-07T06:40:24.546086+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-06-07T06:40:25.113990+00:00 heroku[web.1]: State changed from starting to crashed
2022-06-07T06:40:25.117606+00:00 heroku[web.1]: State changed from crashed to starting
2022-06-07T06:40:40.833980+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-06-07T06:40:42.514288+00:00 app[web.1]: 2022-06-07 06:40:42,514 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-06-07T06:40:43.356065+00:00 app[web.1]: Traceback (most recent call last):
2022-06-07T06:40:43.356087+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-06-07T06:40:43.356165+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-06-07T06:40:43.356173+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-06-07T06:40:43.356262+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-06-07T06:40:43.356271+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-06-07T06:40:43.356340+00:00 app[web.1]:     __import__(pkg_name)
2022-06-07T06:40:43.356347+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 59, in <module>
2022-06-07T06:40:43.356407+00:00 app[web.1]:     srun(["qbittorrent-nox", "-d", "--profile=."])
2022-06-07T06:40:43.356414+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-06-07T06:40:43.356545+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-06-07T06:40:43.356561+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-06-07T06:40:43.356776+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-06-07T06:40:43.356786+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-06-07T06:40:43.357061+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-06-07T06:40:43.357074+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-06-07T06:40:43.662294+00:00 heroku[web.1]: State changed from starting to crashed
2022-06-07T06:40:43.588675+00:00 heroku[web.1]: Process exited with status 1
2022-06-07T06:46:42.851683+00:00 heroku[web.1]: State changed from crashed to down
```

Please help me with this

**Comment by anny414** [comment]
![d05564dd-6741-41ba-afec-e75dfcd5cb08](https://user-images.githubusercontent.com/72495984/172315227-50ceb985-7cd1-4091-a927-f5275b60a798.jpg)
}

**Comment by OAJJAIN** [comment]
Refork and deploy again

**Comment by anasty17** [comment]
Deploy heroku branch not master
