### ISSUE TITLE
uploads are stuck

### ISSUE THREAD

**Issue by raiden076** [anasty17/mirror-leech-telegram-bot#734]
**Describe the bug**
All my uploads are stuck at the beginning, 

**To Reproduce**
1. Used mirror/unzipmirror/qbmirror or whatever Command with any torrent or direct link
2. before/while Upload ..
3. Check logs

**Expected behavior**
uploads are stuck, in the beginning, and in logs the same thing.

**logs**

$ sudo docker logs -f 886001c6aae0
[2022-07-10 20:43:28 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2022-07-10 20:43:28 +0000] [12] [INFO] Listening at: http://0.0.0.0:6969 (12)
[2022-07-10 20:43:28 +0000] [12] [INFO] Using worker: sync
[2022-07-10 20:43:28 +0000] [37] [INFO] Booting worker with pid: 37
2022-07-10 20:43:30,200 - bot - INFO - Generating BOT_SESSION_STRING
2022-07-10 20:43:30,202 - root - INFO - Initializing Aria2c
2022-07-10 20:43:31,704 - root - WARNING - MEGA API KEY not provided!
2022-07-10 20:43:31,704 - root - WARNING - MEGA Credentials not provided!
2022-07-10 20:43:34,917 - bot - INFO - Creating Telegraph Account
2022-07-10 20:43:40,179 - apscheduler.scheduler - INFO - Scheduler started
2022-07-10 20:43:40,333 - bot - INFO - Bot Started!
2022-07-10 21:26:29,110 - bot - INFO - https://download131.uploadhaven.com/1/application/zip/99eyBH8SkVBG6ewbp7HHRP96IbdI4W0N8mgSrUHz.zip?key=G4cWY-9aETixawAzpO-XBA&expire=1657574744&filename=Apocalyptic.zip
2022-07-10 21:26:33,026 - bot - INFO - No Direct link function found for https://download131.uploadhaven.com/1/application/zip/99eyBH8SkVBG6ewbp7HHRP96IbdI4W0N8mgSrUHz.zip?key=G4cWY-9aETixawAzpO-XBA&expire=1657574744&filename=Apocalyptic.zip
2022-07-10 21:26:33,037 - bot - INFO - Started: 837f1042cb3fe670 DIR: /usr/src/app/downloads/7149
2022-07-10 21:26:40,834 - bot - INFO - onDownloadError: 837f1042cb3fe670
2022-07-10 21:26:41,342 - bot - INFO - Download Error: The response status is not successful. status=403
2022-07-10 21:29:53,694 - bot - INFO - https://download167.uploadhaven.com/1/application/zip/dMDzz8XWHqnt0IBdxGp0x0XMOyl5cNNwkqBDcB5W.zip?key=bx9qlV4WtTK7-7tu6ObnKg&expire=1657574975&filename=Tom.Clancys.Splinter.Cell.Conviction.zip
2022-07-10 21:30:00,053 - bot - INFO - Started: c3444b3abc7ae692 DIR: /usr/src/app/downloads/7158
2022-07-10 21:33:05,947 - bot - INFO - Cancelling Download: Tom.Clancys.Splinter.Cell.Conviction.zip
2022-07-10 21:33:05,951 - bot - INFO - Cleaning Download: /usr/src/app/downloads/7158
2022-07-10 21:33:16,478 - bot - INFO - https://download167.uploadhaven.com/1/application/zip/dMDzz8XWHqnt0IBdxGp0x0XMOyl5cNNwkqBDcB5W.zip?key=bx9qlV4WtTK7-7tu6ObnKg&expire=1657574975&filename=Tom.Clancys.Splinter.Cell.Conviction.zip
2022-07-10 21:33:17,532 - bot - INFO - Started: 00e4c126ecdd2077 DIR: /usr/src/app/downloads/7178
2022-07-10 21:40:34,264 - bot - INFO - https://download131.uploadhaven.com/1/application/zip/NpIPbKeqvWGhAjyud17jcSX9aj7qPaPz4EUsrppJ.zip?key=fX7BQ7VWuAP3ksI6ns-mrg&expire=1657575615&filename=Cyberpunk.2077.v1.52.zip
2022-07-10 21:40:50,966 - bot - INFO - No Direct link function found for https://download131.uploadhaven.com/1/application/zip/NpIPbKeqvWGhAjyud17jcSX9aj7qPaPz4EUsrppJ.zip?key=fX7BQ7VWuAP3ksI6ns-mrg&expire=1657575615&filename=Cyberpunk.2077.v1.52.zip
2022-07-10 21:40:50,977 - bot - INFO - Started: 59d57ab1fbade264 DIR: /usr/src/app/downloads/7194
2022-07-10 21:42:01,161 - bot - INFO - onDownloadComplete: 00e4c126ecdd2077
2022-07-10 21:42:01,172 - bot - INFO - Download completed: Tom.Clancys.Splinter.Cell.Conviction.zip
2022-07-10 21:42:01,178 - bot - INFO - Extracting: Tom.Clancys.Splinter.Cell.Conviction.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs LE)

Scanning the drive for archives:
1 file, 6722454048 bytes (6412 MiB)

Extracting archive: /usr/src/app/downloads/7178/Tom.Clancys.Splinter.Cell.Conviction.zip
2022-07-10 21:42:47,288 - bot - INFO - Cancelling Download: Cyberpunk.2077.v1.52.zip
2022-07-10 21:42:47,292 - bot - INFO - Cleaning Download: /usr/src/app/downloads/7194

Path = /usr/src/app/downloads/7178/Tom.Clancys.Splinter.Cell.Conviction.zip
Type = zip
Physical Size = 6722454048
64-bit = +

Everything is Ok

Folders: 61
Files: 515
Size:       7421420765
Compressed: 6722454048
/usr/src/app
2022-07-10 21:42:58,306 - bot - INFO - Extracted Path: /usr/src/app/downloads/7178/Tom.Clancys.Splinter.Cell.Conviction
2022-07-10 21:42:59,171 - bot - INFO - Upload Name: Tom.Clancys.Splinter.Cell.Conviction
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 53, in __onDownloadComplete
    dl.getListener().onDownloadComplete()
  File "/usr/src/app/bot/modules/mirror.py", line 168, in onDownloadComplete
    drive = GoogleDriveHelper(up_name, self)
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 44, in __init__
    self.__service = self.__authorize()
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 458, in __authorize
    credentials = pload(f)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by anasty17** [comment]
Regenerate token.pickle
