### ISSUE TITLE
YouTube playlist 

### ISSUE THREAD

**Issue by kawinpattanai** [anasty17/mirror-leech-telegram-bot#739]
2022-07-12T13:22:20.748320+00:00 app[web.1]: Exception in thread Thread-6 (add_download):
2022-07-12T13:22:20.748330+00:00 app[web.1]: Traceback (most recent call last):
2022-07-12T13:22:20.748339+00:00 app[web.1]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-07-12T13:22:20.748570+00:00 app[web.1]:     self.run()
2022-07-12T13:22:20.748582+00:00 app[web.1]:   File "/usr/lib/python3.10/threading.py", line 946, in run
2022-07-12T13:22:20.748741+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2022-07-12T13:22:20.748754+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/youtube_dl_download_helper.py", line 179, in add_download
2022-07-12T13:22:20.748846+00:00 app[web.1]:     self.extractMetaData(link, name, args)
2022-07-12T13:22:20.748859+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/youtube_dl_download_helper.py", line 129, in extractMetaData
2022-07-12T13:22:20.748936+00:00 app[web.1]:     if 'filesize_approx' in v:
2022-07-12T13:22:20.748975+00:00 app[web.1]: TypeError: argument of type 'NoneType' is not iterable

After I try to download playlist

**Comment by anasty17** [comment]
Read report bug guide lines, send link
