### ISSUE TITLE
Upstream Repo can't able to use

### ISSUE THREAD

**Issue by cvatricks** [anasty17/mirror-leech-telegram-bot#810]
**Describe the bug**
I need to modify message texts. So I need to update UPSTREAM_REPO.

When I set UPSTREAM_REPO in config_url, I can't see changes in bot.

But When I set UPSTREAM_REPO and UPSTREAM_BRANCH in config_url. Bot not started &  error as shown below.

**To Reproduce**
2022-07-24T11:09:37.347208+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-07-24T11:09:37.347391+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-07-24T11:09:37.347396+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-07-24T11:09:37.347708+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-07-24T11:09:37.347724+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-07-24T11:09:37.521355+00:00 app[web.1]: [2022-07-24 11:09:37 +0000] [32] [INFO] Starting gunicorn 20.1.0
2022-07-24T11:09:37.521766+00:00 app[web.1]: [2022-07-24 11:09:37 +0000] [32] [ERROR] Retrying in 1 second.
2022-07-24T11:09:37.689539+00:00 heroku[web.1]: Process exited with status 1
2022-07-24T11:09:37.997572+00:00 heroku[web.1]: State changed from starting to crashed
2022-07-24T11:09:38.001451+00:00 heroku[web.1]: State changed from crashed to starting
2022-07-24T11:09:16.632099+00:00 app[api]: Deployed web (be4fa42961b4) by user email.com
2022-07-24T11:09:16.632099+00:00 app[api]: Release v4 created by user email.com
2022-07-24T11:09:16.645558+00:00 app[api]: Scaled to web@1:Free by user email.com
2022-07-24T11:09:50.537330+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-07-24T11:09:52.314575+00:00 app[web.1]: 2022-07-24 11:09:52,314 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-07-24T11:09:53.387138+00:00 app[web.1]: Traceback (most recent call last):
2022-07-24T11:09:53.387191+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-07-24T11:09:53.387371+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-07-24T11:09:53.387387+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-07-24T11:09:53.387496+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-07-24T11:09:53.387510+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-07-24T11:09:53.387607+00:00 app[web.1]:     __import__(pkg_name)
2022-07-24T11:09:53.387622+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 59, in <module>
2022-07-24T11:09:53.387710+00:00 app[web.1]:     srun(["qbittorrent-nox", "-d", "--profile=."])
2022-07-24T11:09:53.387725+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-07-24T11:09:53.387919+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-07-24T11:09:53.387934+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-07-24T11:09:53.388222+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-07-24T11:09:53.388238+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-07-24T11:09:53.388689+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-07-24T11:09:53.388711+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-07-24T11:09:53.587384+00:00 app[web.1]: [2022-07-24 11:09:53 +0000] [31] [INFO] Starting gunicorn 20.1.0
2022-07-24T11:09:53.587879+00:00 app[web.1]: [2022-07-24 11:09:53 +0000] [31] [ERROR] Retrying in 1 second.
2022-07-24T11:09:53.723835+00:00 heroku[web.1]: Process exited with status 1
2022-07-24T11:09:53.788414+00:00 heroku[web.1]: State changed from starting to crashed
**Expected behavior**
I want to use UPSTREAM_REPO as my github fork.

Please help me.

**Comment by anasty17** [comment]
Read readme
