### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by pradeishc** [anasty17/mirror-leech-telegram-bot#854]
warning: no common commits
2022-08-04 05:33:29,823 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
[2022-08-04 05:33:30 +0000] [32] [INFO] Starting gunicorn 20.1.0
[2022-08-04 05:33:30 +0000] [32] [INFO] Listening at: http://0.0.0.0:80 (32)
[2022-08-04 05:33:30 +0000] [32] [INFO] Using worker: sync
[2022-08-04 05:33:30 +0000] [58] [INFO] Booting worker with pid: 58
2022-08-04 05:33:31,943 - bot - INFO - Creating client from USER_SESSION_STRING
2022-08-04 05:33:32,511 - pyrogram.connection.connection - INFO - Connecting...
2022-08-04 05:33:32,557 - pyrogram.connection.connection - INFO - Connected! Production DC5 - IPv4 - TCPAbridgedO
2022-08-04 05:33:32,558 - pyrogram.session.session - INFO - NetworkTask started
2022-08-04 05:33:32,695 - pyrogram.session.internals.msg_id - INFO - Time synced: 2022-08-04 05:33:32.670347 UTC
2022-08-04 05:33:32,823 - pyrogram.session.session - INFO - Session initialized: Layer 143
2022-08-04 05:33:32,823 - pyrogram.session.session - INFO - Device: CPython 3.8.10 - Pyrogram 2.0.30
2022-08-04 05:33:32,823 - pyrogram.session.session - INFO - System: Linux 5.15.0-1013-oracle (EN)
2022-08-04 05:33:32,824 - pyrogram.session.session - INFO - Session started
2022-08-04 05:33:32,878 - pyrogram.session.session - INFO - PingTask started
2022-08-04 05:33:32,942 - pyrogram.session.session - INFO - PingTask stopped
2022-08-04 05:33:32,942 - pyrogram.connection.connection - INFO - Disconnected
2022-08-04 05:33:32,943 - pyrogram.session.session - INFO - NetworkTask stopped
2022-08-04 05:33:32,943 - pyrogram.session.session - INFO - Session stopped
2022-08-04 05:33:32,943 - bot - INFO - Creating client from BOT_TOKEN
2022-08-04 05:33:32,944 - root - INFO - Initializing Aria2c
2022-08-04 05:33:34,445 - root - WARNING - MEGA API KEY not provided!
2022-08-04 05:33:34,446 - root - WARNING - MEGA Credentials not provided!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 12, in <module>
    from .helper.ext_utils.telegraph_helper import telegraph
  File "/usr/src/app/bot/helper/ext_utils/telegraph_helper.py", line 81, in <module>
    telegraph=TelegraphHelper('Mirror-Leech-Telegram-Bot', 'https://github.com/anasty17/mirror-leech-telegram-bot')
  File "/usr/src/app/bot/helper/ext_utils/telegraph_helper.py", line 20, in __init__
    self.create_account()
  File "/usr/src/app/bot/helper/ext_utils/telegraph_helper.py", line 23, in create_account
    self.telegraph.create_account(
  File "/usr/local/lib/python3.8/dist-packages/telegraph/api.py", line 102, in create_account
    response = self._telegraph.method('createAccount', values={
  File "/usr/local/lib/python3.8/dist-packages/telegraph/api.py", line 29, in method
    response = self.session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by pradeishc** [comment]
This site "https://telegra.ph/" not working

**Comment by anasty17** [comment]
Know issue telegra.ph blocked in india

**Comment by pradeishc** [comment]
Do you have any other solution ?

**Comment by Dawn-India** [comment]
> Do you have any other solution ?

Try using graph.org

**Comment by Tysonmovierulz** [comment]
Anas Bro,try to use space Bin instead of telegra.ph

**Comment by anasty17** [comment]
Replace what! Just wait. U can't create account, by changing? Changing what ? Which link ? Which line in code ?

**Comment by MaxxRider** [comment]
telegra.ph is now 👉   **graph.org**

**Comment by Dawn-India** [comment]
> telegra.ph is now 👉 **graph.org**

I told this exact same thing and he deleted my comment 🤣. You can see above.

**Comment by anasty17** [comment]
> > telegra.ph is now 👉 **graph.org**
> 
> I told this exact same thing and he deleted my comment 🤣. You can see above.

https://github.com/anasty17/mirror-leech-telegram-bot/pull/866#issuecomment-1207168017
Laugh on ur self stupid!

**Comment by anasty17** [comment]
Fixed
