### ISSUE TITLE
Error But Before This Fine After restrat error

### ISSUE THREAD

**Issue by BangKuntet** [anasty17/mirror-leech-telegram-bot#912]
2022-08-15T01:29:07.868984+00:00 app[web.1]:     if not DOWNLOAD_DIR.endswith("/"):
2022-08-15T01:29:07.868984+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'endswith'
2022-08-15T01:29:07.869077+00:00 app[web.1]: [2022-08-15 01:29:07 +0000] [33] [INFO] Worker exiting (pid: 33)
2022-08-15T01:29:07.945867+00:00 app[web.1]: [2022-08-15 01:29:07 +0000] [32] [INFO] Shutting down: Master
2022-08-15T01:29:07.946724+00:00 app[web.1]: [2022-08-15 01:29:07 +0000] [32] [INFO] Reason: Worker failed to boot.
2022-08-15T01:29:09.054710+00:00 app[web.1]: 2022-08-15 01:29:09,054 - root - ERROR - One or more env variables missing! Exiting now
2022-08-15T01:29:09.159753+00:00 app[web.1]: 2022-08-15 01:29:09,159 - asyncio - ERROR - Unclosed client session
2022-08-15T01:29:09.159754+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7f8702ed6ce0>
2022-08-15T01:29:09.396463+00:00 heroku[web.1]: Process exited with status 1
2022-08-15T01:29:09.581863+00:00 heroku[web.1]: State changed from up to crashed
2022-08-15T01:41:15.071006+00:00 heroku[web.1]: State changed from crashed to starting
2022-08-15T01:41:25.705746+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-08-15T01:41:27.302838+00:00 app[web.1]: 2022-08-15 01:41:27,302 - root - ERROR - Failed to download config.env 404
2022-08-15T01:41:29.250066+00:00 app[web.1]: 2022-08-15 01:41:29,249 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-15T01:41:30.679723+00:00 app[web.1]: [2022-08-15 01:41:30 +0000] [32] [INFO] Starting gunicorn 20.1.0
2022-08-15T01:41:30.680058+00:00 app[web.1]: [2022-08-15 01:41:30 +0000] [32] [INFO] Listening at: http://0.0.0.0:9008 (32)
2022-08-15T01:41:30.680102+00:00 app[web.1]: [2022-08-15 01:41:30 +0000] [32] [INFO] Using worker: sync
2022-08-15T01:41:30.683888+00:00 app[web.1]: [2022-08-15 01:41:30 +0000] [33] [INFO] Booting worker with pid: 33
2022-08-15T01:41:31.133922+00:00 app[web.1]: [2022-08-15 01:41:31 +0000] [33] [ERROR] Exception in worker process
2022-08-15T01:41:31.133934+00:00 app[web.1]: Traceback (most recent call last):
2022-08-15T01:41:31.133935+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-08-15T01:41:31.133936+00:00 app[web.1]:     worker.init_process()
2022-08-15T01:41:31.133936+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
2022-08-15T01:41:31.133936+00:00 app[web.1]:     self.load_wsgi()
2022-08-15T01:41:31.133937+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-08-15T01:41:31.133937+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2022-08-15T01:41:31.133937+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
2022-08-15T01:41:31.133938+00:00 app[web.1]:     self.callable = self.load()
2022-08-15T01:41:31.133938+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-08-15T01:41:31.133938+00:00 app[web.1]:     return self.load_wsgiapp()
2022-08-15T01:41:31.133939+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-08-15T01:41:31.133939+00:00 app[web.1]:     return util.import_app(self.app_uri)
2022-08-15T01:41:31.133939+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
2022-08-15T01:41:31.133940+00:00 app[web.1]:     mod = importlib.import_module(module)
2022-08-15T01:41:31.133940+00:00 app[web.1]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-08-15T01:41:31.133941+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-08-15T01:41:31.133941+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-08-15T01:41:31.133942+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-08-15T01:41:31.133942+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-08-15T01:41:31.133942+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-08-15T01:41:31.133943+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-08-15T01:41:31.133944+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-08-15T01:41:31.133944+00:00 app[web.1]:   File "/usr/src/app/web/wserver.py", line 7, in <module>
2022-08-15T01:41:31.133944+00:00 app[web.1]:     from web.nodes import make_tree
2022-08-15T01:41:31.133945+00:00 app[web.1]:   File "/usr/src/app/web/nodes.py", line 6, in <module>
2022-08-15T01:41:31.133945+00:00 app[web.1]:     if not DOWNLOAD_DIR.endswith("/"):
2022-08-15T01:41:31.133946+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'endswith'
2022-08-15T01:41:31.133951+00:00 app[web.1]: [2022-08-15 01:41:31 +0000] [33] [INFO] Worker exiting (pid: 33)
2022-08-15T01:41:31.198989+00:00 app[web.1]: [2022-08-15 01:41:31 +0000] [32] [INFO] Shutting down: Master
2022-08-15T01:41:31.199035+00:00 app[web.1]: [2022-08-15 01:41:31 +0000] [32] [INFO] Reason: Worker failed to boot.
2022-08-15T01:41:32.691951+00:00 app[web.1]: 2022-08-15 01:41:32,691 - root - ERROR - One or more env variables missing! Exiting now
2022-08-15T01:41:32.821221+00:00 app[web.1]: 2022-08-15 01:41:32,820 - asyncio - ERROR - Unclosed client session
2022-08-15T01:41:32.821223+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7f14335e2ce0>
2022-08-15T01:41:33.214656+00:00 heroku[web.1]: Process exited with status 1
2022-08-15T01:41:33.446530+00:00 heroku[web.1]: State changed from starting to crashed
2022-08-15T01:41:33.450098+00:00 heroku[web.1]: State changed from crashed to starting
2022-08-15T01:41:44.737039+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-08-15T01:41:46.388555+00:00 app[web.1]: 2022-08-15 01:41:46,387 - root - ERROR - Failed to download config.env 404
2022-08-15T01:41:47.597220+00:00 app[web.1]: 2022-08-15 01:41:47,597 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-15T01:41:49.260810+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [32] [INFO] Starting gunicorn 20.1.0
2022-08-15T01:41:49.261150+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [32] [INFO] Listening at: http://0.0.0.0:11525 (32)
2022-08-15T01:41:49.261197+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [32] [INFO] Using worker: sync
2022-08-15T01:41:49.264676+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [33] [INFO] Booting worker with pid: 33
2022-08-15T01:41:49.499930+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [33] [ERROR] Exception in worker process
2022-08-15T01:41:49.499931+00:00 app[web.1]: Traceback (most recent call last):
2022-08-15T01:41:49.499932+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-08-15T01:41:49.499933+00:00 app[web.1]:     worker.init_process()
2022-08-15T01:41:49.499934+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
2022-08-15T01:41:49.499935+00:00 app[web.1]:     self.load_wsgi()
2022-08-15T01:41:49.499935+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-08-15T01:41:49.499937+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2022-08-15T01:41:49.499937+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
2022-08-15T01:41:49.499937+00:00 app[web.1]:     self.callable = self.load()
2022-08-15T01:41:49.499938+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-08-15T01:41:49.499938+00:00 app[web.1]:     return self.load_wsgiapp()
2022-08-15T01:41:49.499939+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-08-15T01:41:49.499939+00:00 app[web.1]:     return util.import_app(self.app_uri)
2022-08-15T01:41:49.499939+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
2022-08-15T01:41:49.499940+00:00 app[web.1]:     mod = importlib.import_module(module)
2022-08-15T01:41:49.499940+00:00 app[web.1]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-08-15T01:41:49.499941+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-08-15T01:41:49.499941+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-08-15T01:41:49.499941+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-08-15T01:41:49.499942+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-08-15T01:41:49.499942+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-08-15T01:41:49.499942+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-08-15T01:41:49.499943+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-08-15T01:41:49.499943+00:00 app[web.1]:   File "/usr/src/app/web/wserver.py", line 7, in <module>
2022-08-15T01:41:49.499943+00:00 app[web.1]:     from web.nodes import make_tree
2022-08-15T01:41:49.499944+00:00 app[web.1]:   File "/usr/src/app/web/nodes.py", line 6, in <module>
2022-08-15T01:41:49.499944+00:00 app[web.1]:     if not DOWNLOAD_DIR.endswith("/"):
2022-08-15T01:41:49.499944+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'endswith'
2022-08-15T01:41:49.500173+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [33] [INFO] Worker exiting (pid: 33)
2022-08-15T01:41:49.583662+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [32] [INFO] Shutting down: Master
2022-08-15T01:41:49.583689+00:00 app[web.1]: [2022-08-15 01:41:49 +0000] [32] [INFO] Reason: Worker failed to boot.
2022-08-15T01:41:51.533512+00:00 heroku[web.1]: State changed from starting to crashed
2022-08-15T01:41:51.487014+00:00 heroku[web.1]: Process exited with status 1
2022-08-15T01:41:51.111840+00:00 app[web.1]: 2022-08-15 01:41:51,111 - root - ERROR - One or more env variables missing! Exiting now
2022-08-15T01:41:51.233299+00:00 app[web.1]: 2022-08-15 01:41:51,233 - asyncio - ERROR - Unclosed client session
2022-08-15T01:41:51.233300+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7faf00ee6ce0>

**Comment by anasty17** [comment]
Issue in ur config file url with status code 404.
Read the error!
