### ISSUE TITLE
Heroku bash start.sh Issue

### ISSUE THREAD

**Issue by telugucartoons1** [anasty17/mirror-leech-telegram-bot#940]
Logs

2022-08-19T04:58:21.892474+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-08-19T04:58:23.526029+00:00 app[web.1]: 2022-08-19 04:58:23,525 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-19T04:58:24.671967+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T04:58:24.671990+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-08-19T04:58:24.672114+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-08-19T04:58:24.672123+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-08-19T04:58:24.672234+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-08-19T04:58:24.672237+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-08-19T04:58:24.672368+00:00 app[web.1]:     __import__(pkg_name)
2022-08-19T04:58:24.672401+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 63, in <module>
2022-08-19T04:58:24.672516+00:00 app[web.1]:     srun(["firefox", "-d", "--profile=."])
2022-08-19T04:58:24.672533+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-08-19T04:58:24.672701+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-08-19T04:58:24.672720+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-08-19T04:58:24.672967+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-08-19T04:58:24.672986+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-08-19T04:58:24.673449+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-08-19T04:58:24.673483+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'firefox'
2022-08-19T04:58:24.808090+00:00 app[web.1]: 2022-08-19 04:58:24,807 - asyncio - ERROR - Unclosed client session
2022-08-19T04:58:24.808092+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7f8b700d46d0>
2022-08-19T04:58:24.882774+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [32] [INFO] Starting gunicorn 20.1.0
2022-08-19T04:58:24.883272+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [32] [INFO] Listening at: http://0.0.0.0:27678 (32)
2022-08-19T04:58:24.883356+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [32] [INFO] Using worker: sync
2022-08-19T04:58:24.889989+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [33] [INFO] Booting worker with pid: 33
2022-08-19T04:58:25.033632+00:00 heroku[web.1]: Process exited with status 1
2022-08-19T04:58:25.112496+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by kyash4** [comment]
Yes Same problem with me also

**Comment by kyash4** [comment]
> Logs
> 
> 2022-08-19T04:58:21.892474+00:00 heroku[web.1]: Starting process with command `bash start.sh` 2022-08-19T04:58:23.526029+00:00 app[web.1]: 2022-08-19 04:58:23,525 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO 2022-08-19T04:58:24.671967+00:00 app[web.1]: Traceback (most recent call last): 2022-08-19T04:58:24.671990+00:00 app[web.1]: File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main 2022-08-19T04:58:24.672114+00:00 app[web.1]: mod_name, mod_spec, code = _get_module_details(mod_name, _Error) 2022-08-19T04:58:24.672123+00:00 app[web.1]: File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details 2022-08-19T04:58:24.672234+00:00 app[web.1]: return _get_module_details(pkg_main_name, error) 2022-08-19T04:58:24.672237+00:00 app[web.1]: File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details 2022-08-19T04:58:24.672368+00:00 app[web.1]: **import**(pkg_name) 2022-08-19T04:58:24.672401+00:00 app[web.1]: File "/usr/src/app/bot/**init**.py", line 63, in 2022-08-19T04:58:24.672516+00:00 app[web.1]: srun(["firefox", "-d", "--profile=."]) 2022-08-19T04:58:24.672533+00:00 app[web.1]: File "/usr/lib/python3.10/subprocess.py", line 501, in run 2022-08-19T04:58:24.672701+00:00 app[web.1]: with Popen(*popenargs, **kwargs) as process: 2022-08-19T04:58:24.672720+00:00 app[web.1]: File "/usr/lib/python3.10/subprocess.py", line 966, in **init** 2022-08-19T04:58:24.672967+00:00 app[web.1]: self._execute_child(args, executable, preexec_fn, close_fds, 2022-08-19T04:58:24.672986+00:00 app[web.1]: File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child 2022-08-19T04:58:24.673449+00:00 app[web.1]: raise child_exception_type(errno_num, err_msg, err_filename) 2022-08-19T04:58:24.673483+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'firefox' 2022-08-19T04:58:24.808090+00:00 app[web.1]: 2022-08-19 04:58:24,807 - asyncio - ERROR - Unclosed client session 2022-08-19T04:58:24.808092+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7f8b700d46d0> 2022-08-19T04:58:24.882774+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [32] [INFO] Starting gunicorn 20.1.0 2022-08-19T04:58:24.883272+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [32] [INFO] Listening at: http://0.0.0.0:27678 (32) 2022-08-19T04:58:24.883356+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [32] [INFO] Using worker: sync 2022-08-19T04:58:24.889989+00:00 app[web.1]: [2022-08-19 04:58:24 +0000] [33] [INFO] Booting worker with pid: 33 2022-08-19T04:58:25.033632+00:00 heroku[web.1]: Process exited with status 1 2022-08-19T04:58:25.112496+00:00 heroku[web.1]: State changed from starting to crashed

You have to remove the app and deploying again.

**Comment by telugucartoons1** [comment]
oh k

**Comment by telugucartoons1** [comment]
again its showing like that

**Comment by telugucartoons1** [comment]
Logs

2022-08-19T05:53:36.762061+00:00 app[web.1]: 2022-08-19 05:53:36,761 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4fd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /
2022-08-19T05:53:36.763854+00:00 app[web.1]: 2022-08-19 05:53:36,763 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f99fcb4ece0>: Failed to establish a new connection: [Errno 111] Connection refused')': /
2022-08-19T05:53:36.767232+00:00 app[web.1]: 2022-08-19 05:53:36,767 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4e6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/auth/login
2022-08-19T05:53:36.769555+00:00 app[web.1]: 2022-08-19 05:53:36,769 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4ffa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /
2022-08-19T05:53:36.771588+00:00 app[web.1]: 2022-08-19 05:53:36,771 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f99fcb4e3e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /
2022-08-19T05:53:36.773861+00:00 app[web.1]: 2022-08-19 05:53:36,773 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4ddb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/auth/login
2022-08-19T05:53:36.777708+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T05:53:36.777709+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2022-08-19T05:53:36.777710+00:00 app[web.1]:     conn = connection.create_connection(
2022-08-19T05:53:36.777711+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
2022-08-19T05:53:36.777711+00:00 app[web.1]:     raise err
2022-08-19T05:53:36.777712+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
2022-08-19T05:53:36.777712+00:00 app[web.1]:     sock.connect(sa)
2022-08-19T05:53:36.777713+00:00 app[web.1]: ConnectionRefusedError: [Errno 111] Connection refused
2022-08-19T05:53:36.777713+00:00 app[web.1]: 
2022-08-19T05:53:36.777714+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-08-19T05:53:36.777714+00:00 app[web.1]: 
2022-08-19T05:53:36.777715+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T05:53:36.777715+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2022-08-19T05:53:36.777715+00:00 app[web.1]:     httplib_response = self._make_request(
2022-08-19T05:53:36.777715+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2022-08-19T05:53:36.777716+00:00 app[web.1]:     conn.request(method, url, **httplib_request_kw)
2022-08-19T05:53:36.777716+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2022-08-19T05:53:36.777716+00:00 app[web.1]:     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2022-08-19T05:53:36.777717+00:00 app[web.1]:   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2022-08-19T05:53:36.777717+00:00 app[web.1]:     self._send_request(method, url, body, headers, encode_chunked)
2022-08-19T05:53:36.777717+00:00 app[web.1]:   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2022-08-19T05:53:36.777718+00:00 app[web.1]:     self.endheaders(body, encode_chunked=encode_chunked)
2022-08-19T05:53:36.777718+00:00 app[web.1]:   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2022-08-19T05:53:36.777718+00:00 app[web.1]:     self._send_output(message_body, encode_chunked=encode_chunked)
2022-08-19T05:53:36.777719+00:00 app[web.1]:   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2022-08-19T05:53:36.777719+00:00 app[web.1]:     self.send(msg)
2022-08-19T05:53:36.777719+00:00 app[web.1]:   File "/usr/lib/python3.10/http/client.py", line 975, in send
2022-08-19T05:53:36.777719+00:00 app[web.1]:     self.connect()
2022-08-19T05:53:36.777720+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2022-08-19T05:53:36.777720+00:00 app[web.1]:     conn = self._new_conn()
2022-08-19T05:53:36.777720+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2022-08-19T05:53:36.777721+00:00 app[web.1]:     raise NewConnectionError(
2022-08-19T05:53:36.777721+00:00 app[web.1]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f99fcb4dc00>: Failed to establish a new connection: [Errno 111] Connection refused
2022-08-19T05:53:36.777721+00:00 app[web.1]: 
2022-08-19T05:53:36.777722+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-08-19T05:53:36.777722+00:00 app[web.1]: 
2022-08-19T05:53:36.777722+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T05:53:36.777722+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2022-08-19T05:53:36.777723+00:00 app[web.1]:     resp = conn.urlopen(
2022-08-19T05:53:36.777723+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
2022-08-19T05:53:36.777724+00:00 app[web.1]:     return self.urlopen(
2022-08-19T05:53:36.777724+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2022-08-19T05:53:36.777725+00:00 app[web.1]:     retries = retries.increment(
2022-08-19T05:53:36.777725+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2022-08-19T05:53:36.777725+00:00 app[web.1]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2022-08-19T05:53:36.777726+00:00 app[web.1]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4dc00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-08-19T05:53:36.777726+00:00 app[web.1]: 
2022-08-19T05:53:36.777726+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-08-19T05:53:36.777727+00:00 app[web.1]: 
2022-08-19T05:53:36.777727+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T05:53:36.777727+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 401, in _request_manager
2022-08-19T05:53:36.777727+00:00 app[web.1]:     return self._request(**kwargs)
2022-08-19T05:53:36.777728+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 452, in _request
2022-08-19T05:53:36.777728+00:00 app[web.1]:     response = self._session.request(
2022-08-19T05:53:36.777728+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 562, in request
2022-08-19T05:53:36.777728+00:00 app[web.1]:     return super(QbittorrentSession, self).request(method, url, **kwargs)
2022-08-19T05:53:36.777729+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2022-08-19T05:53:36.777729+00:00 app[web.1]:     resp = self.send(prep, **send_kwargs)
2022-08-19T05:53:36.777729+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2022-08-19T05:53:36.777730+00:00 app[web.1]:     r = adapter.send(request, **kwargs)
2022-08-19T05:53:36.777730+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2022-08-19T05:53:36.777730+00:00 app[web.1]:     raise ConnectionError(e, request=request)
2022-08-19T05:53:36.777735+00:00 app[web.1]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4dc00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-08-19T05:53:36.777736+00:00 app[web.1]: 
2022-08-19T05:53:36.777736+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-08-19T05:53:36.777736+00:00 app[web.1]: 
2022-08-19T05:53:36.777736+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T05:53:36.777737+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2022-08-19T05:53:36.777737+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-08-19T05:53:36.777738+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2022-08-19T05:53:36.777738+00:00 app[web.1]:     exec(code, run_globals)
2022-08-19T05:53:36.777738+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 18, in <module>
2022-08-19T05:53:36.777739+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror_leech, clone, ytdlp, shell, eval, delete, count, leech_settings, search, rss, bt_select, sleep
2022-08-19T05:53:36.777739+00:00 app[web.1]:   File "/usr/src/app/bot/modules/search.py", line 18, in <module>
2022-08-19T05:53:36.777739+00:00 app[web.1]:     qb_plugins = qbclient.search_plugins()
2022-08-19T05:53:36.777740+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 207, in wrapper
2022-08-19T05:53:36.777740+00:00 app[web.1]:     if v(client.app_web_api_version()) < v(version_introduced):
2022-08-19T05:53:36.777740+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 135, in wrapper
2022-08-19T05:53:36.777741+00:00 app[web.1]:     result = func(client, *args, **kwargs)
2022-08-19T05:53:36.777741+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 90, in wrapper
2022-08-19T05:53:36.777741+00:00 app[web.1]:     client.auth_log_in(**get_requests_kwargs(**kwargs))
2022-08-19T05:53:36.777742+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/auth.py", line 96, in auth_log_in
2022-08-19T05:53:36.777742+00:00 app[web.1]:     self._post(_name=APINames.Authorization, _method="login", data=creds, **kwargs)
2022-08-19T05:53:36.777742+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 350, in _post
2022-08-19T05:53:36.777744+00:00 app[web.1]:     return self._request_manager(
2022-08-19T05:53:36.777744+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 411, in _request_manager
2022-08-19T05:53:36.777744+00:00 app[web.1]:     raise APIConnectionError(error_message, response=response)
2022-08-19T05:53:36.777756+00:00 app[web.1]: qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99fcb4dc00>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
2022-08-19T05:53:15.853729+00:00 app[api]: Scaled to web@1:Free by user ironmanymirrortele@gmail.com

**Comment by rahulmadhav17** [comment]
yes for me too

**Comment by oneironaut2209** [comment]
Same error for me too. Try redeploying too.

Logs:

> 2022-08-19T06:17:19.743757+00:00 heroku[web.1]: State changed from crashed to starting
2022-08-19T06:17:31.698950+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-08-19T06:17:33.135394+00:00 app[web.1]: 2022-08-19 06:17:33,135 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-19T06:17:34.251917+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [31] [INFO] Starting gunicorn 20.1.0
2022-08-19T06:17:34.252230+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [31] [INFO] Listening at: http://0.0.0.0:10690 (31)
2022-08-19T06:17:34.252433+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [31] [INFO] Using worker: sync
2022-08-19T06:17:34.255521+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [32] [INFO] Booting worker with pid: 32
2022-08-19T06:17:34.552162+00:00 heroku[web.1]: State changed from starting to up
2022-08-19T06:17:34.695259+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [32] [ERROR] Exception in worker process
2022-08-19T06:17:34.695270+00:00 app[web.1]: Traceback (most recent call last):
2022-08-19T06:17:34.695271+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-08-19T06:17:34.695272+00:00 app[web.1]:     worker.init_process()
2022-08-19T06:17:34.695274+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
2022-08-19T06:17:34.695274+00:00 app[web.1]:     self.load_wsgi()
2022-08-19T06:17:34.695274+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-08-19T06:17:34.695275+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2022-08-19T06:17:34.695275+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
2022-08-19T06:17:34.695275+00:00 app[web.1]:     self.callable = self.load()
2022-08-19T06:17:34.695276+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-08-19T06:17:34.695276+00:00 app[web.1]:     return self.load_wsgiapp()
2022-08-19T06:17:34.695276+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-08-19T06:17:34.695277+00:00 app[web.1]:     return util.import_app(self.app_uri)
2022-08-19T06:17:34.695277+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
2022-08-19T06:17:34.695277+00:00 app[web.1]:     mod = importlib.import_module(module)
2022-08-19T06:17:34.695278+00:00 app[web.1]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-08-19T06:17:34.695278+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-08-19T06:17:34.695279+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-08-19T06:17:34.695279+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-08-19T06:17:34.695280+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-08-19T06:17:34.695280+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-08-19T06:17:34.695280+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-08-19T06:17:34.695280+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-08-19T06:17:34.695281+00:00 app[web.1]:   File "/usr/src/app/web/wserver.py", line 7, in <module>
2022-08-19T06:17:34.695281+00:00 app[web.1]:     from web.nodes import make_tree
2022-08-19T06:17:34.695282+00:00 app[web.1]:   File "/usr/src/app/web/nodes.py", line 6, in <module>
2022-08-19T06:17:34.695282+00:00 app[web.1]:     if not DOWNLOAD_DIR.endswith("/"):
2022-08-19T06:17:34.695282+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'endswith'
2022-08-19T06:17:34.695448+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [32] [INFO] Worker exiting (pid: 32)
2022-08-19T06:17:34.765369+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [31] [INFO] Shutting down: Master
2022-08-19T06:17:34.765398+00:00 app[web.1]: [2022-08-19 06:17:34 +0000] [31] [INFO] Reason: Worker failed to boot.
2022-08-19T06:17:36.095160+00:00 app[web.1]: 2022-08-19 06:17:36,094 - root - ERROR - One or more env variables missing! Exiting now
2022-08-19T06:17:36.181477+00:00 app[web.1]: 2022-08-19 06:17:36,181 - asyncio - ERROR - Unclosed client session
2022-08-19T06:17:36.181479+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7effd5de2e30>
2022-08-19T06:17:36.413832+00:00 heroku[web.1]: Process exited with status 1
2022-08-19T06:17:36.526054+00:00 heroku[web.1]: State changed from up to crashed

**Comment by svampebobber** [comment]
delete your repo and refork again. Delete the app aswell. Anas made changes to code

**Comment by anasty17** [comment]
Read the errror . Variable missing

**Comment by telugucartoons1** [comment]
![image](https://user-images.githubusercontent.com/88655760/185607339-62a18eec-b819-4f5f-96fd-103a8239cc2d.png)

**Comment by telugucartoons1** [comment]
![image](https://user-images.githubusercontent.com/88655760/185607512-3316a3e1-012f-4d40-a307-dc2c12fa3f46.png)

**Comment by telugucartoons1** [comment]
![image](https://user-images.githubusercontent.com/88655760/185607823-106d8bbc-e583-47c6-b2bf-250fdef3d221.png)

**Comment by telugucartoons1** [comment]
See I Have Filled Everything Right Only

**Comment by anasty17** [comment]
Send log file don't copy paste text i can't see anything
