### ISSUE TITLE
Unable to start on heroku

### ISSUE THREAD

**Issue by a0v0** [anasty17/mirror-leech-telegram-bot#957]
```
2022-08-20T08:42:50.642663+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-08-20T08:42:52.155663+00:00 app[web.1]: 2022-08-20 08:42:52,155 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-20T08:42:53.158944+00:00 app[web.1]: Traceback (most recent call last):
2022-08-20T08:42:53.158958+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-08-20T08:42:53.159061+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-08-20T08:42:53.159063+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-08-20T08:42:53.159135+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-08-20T08:42:53.159137+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-08-20T08:42:53.159207+00:00 app[web.1]:     __import__(pkg_name)
2022-08-20T08:42:53.159209+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 59, in <module>
2022-08-20T08:42:53.159267+00:00 app[web.1]:     srun(["qbittorrent-nox", "-d", "--profile=."])
2022-08-20T08:42:53.159269+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-08-20T08:42:53.159403+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-08-20T08:42:53.159403+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-08-20T08:42:53.159585+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-08-20T08:42:53.159588+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-08-20T08:42:53.159934+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-08-20T08:42:53.159947+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-08-20T08:42:53.314412+00:00 app[web.1]: [2022-08-20 08:42:53 +0000] [32] [INFO] Starting gunicorn 20.1.0
2022-08-20T08:42:53.314710+00:00 app[web.1]: [2022-08-20 08:42:53 +0000] [32] [ERROR] Retrying in 1 second.
2022-08-20T08:42:53.452224+00:00 heroku[web.1]: Process exited with status 1
2022-08-20T08:42:53.511365+00:00 heroku[web.1]: State changed from starting to crashed
2022-08-20T08:42:53.515967+00:00 heroku[web.1]: State changed from crashed to starting
2022-08-20T08:43:05.741894+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-08-20T08:43:07.369147+00:00 app[web.1]: 2022-08-20 08:43:07,368 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-20T08:43:08.249381+00:00 app[web.1]: Traceback (most recent call last):
2022-08-20T08:43:08.249393+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-08-20T08:43:08.249520+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-08-20T08:43:08.249530+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-08-20T08:43:08.249633+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-08-20T08:43:08.249642+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-08-20T08:43:08.249734+00:00 app[web.1]:     __import__(pkg_name)
2022-08-20T08:43:08.249736+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 59, in <module>
2022-08-20T08:43:08.249825+00:00 app[web.1]:     srun(["qbittorrent-nox", "-d", "--profile=."])
2022-08-20T08:43:08.249836+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-08-20T08:43:08.250020+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-08-20T08:43:08.250030+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-08-20T08:43:08.250305+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-08-20T08:43:08.250306+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-08-20T08:43:08.250738+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-08-20T08:43:08.250753+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'qbittorrent-nox'
2022-08-20T08:43:08.564071+00:00 heroku[web.1]: Process exited with status 1
2022-08-20T08:43:08.643709+00:00 heroku[web.1]: State changed from starting to crashed```

**Comment by kyash4** [comment]
Have you redeployed the bot by removing the app and push it back again after updating the code you are going to upload?
