### ISSUE TITLE
Bot not recognizing the torrent with qbit

### ISSUE THREAD

**Issue by Nobody12541** [anasty17/mirror-leech-telegram-bot#994]
So after the last commit the bot isn't leeching with qbit. Mirror is working fine. But the qbmirror isn't working at all.
If there is anthing wrong on my part, please lemme know.
Thanks

**Comment by anasty17** [comment]
Logs!

**Comment by Nobody12541** [comment]
2022-08-28 08:19:17,196 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-08-28 08:19:21,132 - root - INFO - Creating client from BOT_TOKEN
2022-08-28 08:19:21,133 - root - INFO - Initializing Aria2c
2022-08-28 08:19:21,133 - root - INFO - MEGA_API_KEY not provided!
2022-08-28 08:19:46,765 - apscheduler.scheduler - INFO - Scheduler started
2022-08-28 08:19:46,786 - bot - INFO - Bot Started!
2022-08-28 08:19:46,809 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/mirror_leech.py", line 214, in qb_mirror
    _mirror_leech(context.bot, update.message, isQbit=True)
  File "/usr/src/app/bot/modules/mirror_leech.py", line 71, in _mirror_leech
    link = re_split(r"pswd:|\|", link)[0]
UnboundLocalError: local variable 'link' referenced before assignment

**Comment by Nobody12541** [comment]
> Logs!

Sorry for not providing it above. I just pasted it above

**Comment by anasty17** [comment]
> > Logs!
> 
> Sorry for not providing it above. I just pasted it

Don't report after modifying the code
